#    Copyright 2020 Australian Institute of Marine Science
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

#' fit_model_set
#'
#' Conducts a full subsets analysis based on gam(m4) using the list generated by a call to generate_model_set
#' @param model.set.list A list as returned by generate_model_set()
#'
#' @param max.models The total number of models allowed to be fit and the model fits to be saved during fitting. Defaults to 200. If the candidate set is bigger than this value, a warning message will be returned.
#'
#' @param save.model.fits Should all successfully fitted models be saved to list success.models. Defaults to TRUE. Value is overwritten if the number of models n the set is bigger than max.models.
#'
#' @param parallel  A logical value indicating if parallel processing should be used. The default is FALSE.
#'
#' @param n.cores An integer indicating the number of cores to use if parallel is TRUE. Defaults to 4.
#'
#' @param r2.type The value to extract from the gam model fit to use as the R squared value. Defaults to r2.lm.est which returns and estimated R squared value based on a linear regression between the observed and predicted values. r2 will return the adjusted R.sq as reported by gam, gamm or gamm4.dev will return the deviance explained as reported by gam or gamm. Note gamm4 does not currently return a deviance.
#'
#' @param  report.unique.r2 The estimated null model R2 is subtracted from each model R2 to give an idea of the unique variance explained. This can be useful where null terms are included in the model set.
#'
#' @param  VI.mods The set of models used to calculate summed variable importance scores. Defaults to 'min.n', which uses only the best n models for each variable (n being the minimum number of models any one predictor is present in). Set to 'all' to use all models in the candidate set instead.
#'
#' @details The function constructs and fits a complete model set based on the supplied arguments.
#' for more information see Fisher R, Wilson SK, Sin TM, Lee AC, Langlois TJ (2018) A simple function for full-subsets multiple regression in ecology with R. Ecology and Evolution
#' https://onlinelibrary.wiley.com/doi/abs/10.1002/ece3.4134
#' @export
#' @return A list of the following output files:
#'
#' mod.data.out - A data.frame that contains the statistics associated with each model fit. This includes AICc and BIC, delta values (e.g. AICc-(min(AICc)), corresponding weight values (Burnham and Anderson 2003), an estimate of the model R2, and a column for each of the included predictor variables containing either 0 (variable not included in the model) or 1 (variable is present in the model).
#' Use of BIC in information theoretic approaches has been heavily criticised because of the inherent assumption of BIC that there is a true model that is represented in the candidate set (Anderson & Burnham 2002). Rather than decide a-priori which model selection tool users should adopt, we supply both as part of the function outputs.
#' To simplify output, only AICc and AICc based model weights, rather than AIC, are included as these are asymptotically equivalent at large sample sizes, and for small sample sizes AICc should be used in any case.
#' Calculating R2 values is non-trivial for mixed models, especially non-gaussian cases (and some argue should not be done at all). We have supplied a range of methods for estimating R2 (r2.type), as in our experience a single method rarely performs adequately across all scenarios.
#'
#' failed.models - A list of model formula that failed to fit. Ideally the list of failed models should be empty, but when this is not the case interrogating failed.models provides a useful means of troubleshooting. Users can examine which models are not fitting and explore the reasons for this by fitting the failed models outside the full_subsets_gam call based on the listed formula. When a large number of models fail to fit properly it usually indicates poor specification of the initial test.fit or other arguments in the call to full_subsets_gam (such as the inclusion of factor interactions when there are few data within each level of the factor), or that inappropriate variables are being included in the model set.
#'
#' success.models - A complete list of all successfully fitted model formula. If models were saved, this can be used for multimodel inference and creating model averaged predictions.
#' otherwise the formula can be used to refit the top model set via a call to update of the test fit: update(test.fit,formula=mod.formula[[l]])
#'
#' variable.importance - A list containing importance scores for each included predictor.
#' To determine the relative importance of each predictor across the whole model set we summed the wi values for all models containing each variable.
#' The higher the combined weights for an explanatory parameter, the more important it is in the analysis (Burnham & Anderson, 2002).
#' An assumption of the use of summed model weights to infer variable importance is that the number of models in which the different predictors are present is uniform.
#' As our function removes models with correlated predictors, this is not always the case.
#' To overcome this issue, the summed variable.importance scores are the summed weights for the best n models, where n is equal to the minimum number of models any one predictor is present in.
#' If you would like the variable importance scores to be based on all models in the set instead, set VI.mods="all".
#' @examples
#' library(mgcv)
#' data(case_study1)
#' use.dat <- case_study1
#' use.dat$site <- as.factor(use.dat$site)
#' test.fit <- gam(Herbivore.abundance ~ s(depth, k = 3, bs = "cr") + s(site, bs = "re"),
#'                  family = tw(), data = use.dat)
#' model.set <- generate_model_set(
#'   use.dat = use.dat,
#'   test.fit = test.fit,
#'   pred.vars.cont = c("complexity", "depth"),
#'   pred.vars.fact = "ZONE",
#'   null.terms = "s(site,bs='re')",
#'   max.predictors = 2,
#'   k = 3
#' )
#' fit_model_set(model.set, parallel = FALSE)
fit_model_set=function(model.set.list,
                          max.models=200,
                          save.model.fits=TRUE,
                          parallel=FALSE,
                          n.cores=4,
                          r2.type="r2.lm.est",
                          report.unique.r2=FALSE,
                          VI.mods='min.n'){

  # An unrecognised r2.type used to reach extract_mod_dat(), which matches it
  # against three literals and leaves the value at NA when none matches, so the
  # whole r2.vals column came back NA with no message. Validated here rather
  # than in extract_mod_dat(), which is exported and documents r2.type. as
  # being passed straight through.
  r2.type <- match.arg(r2.type, c("r2.lm.est", "r2", "dev"))
  # compute_variable_importance() had two if blocks and no else, so an
  # unrecognised VI.mods left both weight objects unassigned and the failure
  # surfaced as "object 'aic.var.weights' not found".
  VI.mods <- match.arg(VI.mods, c("min.n", "all"))

  use.datModSet <- model.set.list$used.data
  n.mods=length(model.set.list$mod.formula)#model.set.list$n.mods
  mod.formula <- model.set.list$mod.formula
  test.fit=model.set.list$test.fit
  included.vars <- model.set.list$included.vars

  if(n.mods>max.models){
        warning(paste("You have ", n.mods," models. Individual models fits will not be saved.
        If you want to save all the model fits all of these you need to
        increase 'max.models' from ", max.models,".", sep=""))
        save.model.fits=FALSE
  }

  ## Now do the model fitting
  if(save.model.fits==TRUE){
    summary.l=fit_and_summarise_saved_models(mod.formula=mod.formula,test.fit=test.fit,
                          use.dat=use.datModSet,n.mods=n.mods,included.vars=included.vars,
                          r2.type=r2.type,parallel=parallel,n.cores=n.cores)
  }else{
    summary.l=fit_and_summarise_unsaved_models(mod.formula=mod.formula,test.fit=test.fit,
                          use.dat=use.datModSet,n.mods=n.mods,included.vars=included.vars,
                          r2.type=r2.type,parallel=parallel,n.cores=n.cores)
  }
  mod.data.out=summary.l$mod.data.out
  failed.models=summary.l$failed.models
  success.models=summary.l$success.models
  var.inclusions=summary.l$var.inclusions

  mod.data.out=compute_model_weights(mod.data.out=mod.data.out,report.unique.r2=report.unique.r2)

  ### now add columns for the included predictors to the dataframe
  mod.data.out <- cbind(mod.data.out,var.inclusions)

  variable.importance=compute_variable_importance(mod.data.out=mod.data.out,
                          included.vars=included.vars,VI.mods=VI.mods)

  # now return the list of outputs
  return(list(mod.data.out=mod.data.out,
              failed.models=failed.models,
              success.models=success.models,
              variable.importance=variable.importance))
} #------------------ end function --------------------------------------------#

# Internal helpers for fit_model_set(). Not exported.

# extract_mod_dat()'s all-NA return, in the unlist()ed form the fitting loops
# collect.
na_mod_dat_row=function(){
  unlist(list(AICc=NA,BIC=NA,r2.vals=NA,r2.vals.unique=NA,edf=NA,edf.less.1=NA))
}

# Replaces anything in the collected list that is not one of those vectors
# with the all-NA row.
#
# Needed because of .errorhandling='pass': a failing element of the foreach()
# comes back as the condition object rather than as a named vector, and
# do.call("rbind", .) over the mixed list produces a malformed table. Once
# replaced, the candidate reaches failed.models via the is.na(AICc) test the
# caller already applies, which is how a fit that returns a try-error is
# already handled.
#
# is.atomic() rather than is.numeric(): the all-NA row is logical, not
# numeric, so is.numeric() would reject rows that are already correct. A
# condition object is a list, so is.atomic() still separates the two.
normalise_mod_dat_rows=function(mod.dat){
  na.row <- na_mod_dat_row()
  ok <- vapply(mod.dat,
               function(x) is.atomic(x) && length(x)==length(na.row),
               logical(1))
  mod.dat[!ok] <- list(na.row)
  mod.dat
}

# Fits every model in mod.formula (parallel or sequential) and keeps the
# fitted model objects, then builds mod.data.out/failed.models/success.models
# from those fits. Used when save.model.fits=TRUE.
fit_and_summarise_saved_models=function(mod.formula,test.fit,use.dat,n.mods,
                          included.vars,r2.type,parallel,n.cores){
  pb <- utils::txtProgressBar(max = length(mod.formula), style = 3)
  progress <- function(n) utils::setTxtProgressBar(pb, n)

  # Resolved once per candidate, here, before any parallel workers are
  # started -- not lazily inside fit_mod_l() on whatever process ends up
  # refitting that candidate. A doSNOW worker never has this (the calling
  # process's) variables in scope, so resolving family on the worker would
  # fail whenever family was supplied via a variable (GitHub issue
  # beckyfisher/FSSgam#10).
  # Resolving per-candidate (rather than once, shared) also keeps every
  # refit's family object independent (GitHub issue beckyfisher/FSSgam#12).
  # See
  # resolve_candidate_family() in R/utils.R.
  family.list <- lapply(seq_len(length(mod.formula)),function(i.) resolve_candidate_family(test.fit))

  if(parallel==TRUE){
   cl=parallel::makeCluster(n.cores)
   doSNOW::registerDoSNOW(cl)
   opts <- list(progress = progress)
   out.dat<-foreach::foreach(l = 1:length(mod.formula),
                   .packages=c('mgcv','gamm4','MuMIn','FSSgam'),
                   .errorhandling='pass',
                   .options.snow = opts)%dopar%{
     fit_mod_l(mod.formula[[l]],test.fit.=test.fit,use.dat=use.dat,family.=family.list[[l]])
  }
   close(pb)
   parallel::stopCluster(cl)
   foreach::registerDoSEQ()
           }else{
      out.dat <- vector("list", length(mod.formula))
      for(l in 1:length(mod.formula)){
         mod.l=fit_mod_l(mod.formula[[l]],test.fit.=test.fit,use.dat=use.dat,family.=family.list[[l]])
         out.dat[[l]]=mod.l
        utils::setTxtProgressBar(pb,l)
         }
  }
  close(pb)
  names(out.dat) <- names(mod.formula)[1:n.mods]

  # find all the models that didn't fit and extract the error messages
  model.success <- lapply(lapply(out.dat,FUN=class),FUN=function(x){
     length(grep("gam",x))>0})
  failed.models <- mod.formula[which(model.success==FALSE)]
  success.models <- out.dat[which(model.success==TRUE)]
  if(length(success.models)==0){
        stop("None of your models fitted successfully. Please check your input objects.")}

  # of the successful models, make a table indicating which variables are included
  var.inclusions <- build_inclusion_mat(included.vars=included.vars,formula.list=success.models)
  # now make a table of all the model summary data
  mod.data.out <- data.frame("modname"=names(success.models))
  mod.data.out$formula <- unlist(lapply(success.models,FUN=function(x){as.character(stats::formula(x)[3])}))
  mod.data.out <- cbind(mod.data.out,do.call("rbind",lapply(success.models,FUN=function(x){
                      unlist(extract_mod_dat(x,r2.type.=r2.type))})))

  return(list(mod.data.out=mod.data.out,failed.models=failed.models,
              success.models=success.models,var.inclusions=var.inclusions))
}

# Fits every model in mod.formula (parallel or sequential), extracting the
# summary statistics immediately and discarding each fitted model object, so
# the model fits themselves are never held in memory. Used when
# save.model.fits=FALSE (i.e. the candidate set is large).
fit_and_summarise_unsaved_models=function(mod.formula,test.fit,use.dat,n.mods,
                          included.vars,r2.type,parallel,n.cores){
  pb <- utils::txtProgressBar(max = length(mod.formula), style = 3)
  progress <- function(n) utils::setTxtProgressBar(pb, n)

  #for all models make a table indicating which variables are included
  var.inclusions <- build_inclusion_mat(included.vars=included.vars,formula.list=mod.formula)
   # now make a table of all the model summary data
  mod.data.out <- data.frame("modname"=names(mod.formula))
  mod.data.out$formula <- unlist(lapply(mod.formula,FUN=function(x){as.character(stats::formula(x))[2]}))

  # See the matching comment in fit_and_summarise_saved_models() above --
  # resolved here, per candidate, before any parallel workers start (GitHub
  # issues beckyfisher/FSSgam#10 and #12).
  family.list <- lapply(seq_len(length(mod.formula)),function(i.) resolve_candidate_family(test.fit))

  if(parallel==TRUE){
   cl <- parallel::makeCluster(n.cores)
   doSNOW::registerDoSNOW(cl)
   opts <- list(progress = progress)
   mod.dat <- foreach::foreach(l = 1:length(mod.formula),
                   .packages=c('mgcv','gamm4','MuMIn','FSSgam'),
                   .errorhandling='pass',
                   .options.snow = opts)%dopar%{
      unlist(extract_mod_dat(fit_mod_l(mod.formula[[l]],test.fit.=test.fit,use.dat=use.dat,family.=family.list[[l]]),
                             r2.type.=r2.type))

   }
   close(pb)
   parallel::stopCluster(cl)
   foreach::registerDoSEQ()
           }else{
      mod.dat=vector("list", length(mod.formula))
      for(l in 1:length(mod.formula)){
        mod.l=fit_mod_l(mod.formula[[l]],test.fit.=test.fit,use.dat=use.dat,family.=family.list[[l]])
        out=unlist(extract_mod_dat(mod.l,r2.type.=r2.type))
        mod.dat[[l]]=out
        utils::setTxtProgressBar(pb,l)
        }
  }
  close(pb)
  names(mod.dat) <- names(mod.formula[1:n.mods])

  mod.dat <- normalise_mod_dat_rows(mod.dat)
  mod.data.out <- cbind(mod.data.out,do.call("rbind",mod.dat))

  failed.models <- mod.formula[which(is.na(mod.data.out$AICc)==TRUE)]
  success.models <- mod.formula[which(is.na(mod.data.out$AICc)==FALSE)]

  return(list(mod.data.out=mod.data.out,failed.models=failed.models,
              success.models=success.models,var.inclusions=var.inclusions))
}

# Adds delta.AICc/delta.BIC/wi.AICc/wi.BIC columns, and optionally subtracts
# the null model's r2 from every model's r2 (report.unique.r2=TRUE).
compute_model_weights=function(mod.data.out,report.unique.r2){
  mod.data.out$delta.AICc <- round(mod.data.out$AICc-min(mod.data.out$AICc,na.rm=TRUE),3)
  mod.data.out$delta.BIC <- round(mod.data.out$BIC-min(mod.data.out$BIC,na.rm=TRUE),3)
  mod.data.out$wi.AICc <- round(wi(mod.data.out$AICc),3)
  mod.data.out$wi.BIC <- round(wi(mod.data.out$BIC),3)

  # substract the null model r2 value from each model r2 value
  if(report.unique.r2==TRUE){
     null.r2 <- mod.data.out$r2.vals[which(mod.data.out$modname=="null")]
     mod.data.out$r2.vals.unique <- mod.data.out$r2.vals-null.r2
   }

  return(mod.data.out)
}

# Sums AICc/BIC weights across the candidate set for each predictor, either
# using only the best n models per variable (VI.mods='min.n', n being the
# minimum number of models any one predictor is present in) or all models
# (VI.mods='all'). mod.data.out must already include the inclusion columns
# (cbind(mod.data.out, var.inclusions)) and the wi.AICc/wi.BIC columns.
compute_variable_importance=function(mod.data.out,included.vars,VI.mods){
   # find the min number of models for each variable
  # drop=FALSE throughout: with a single predictor the [ , ] would otherwise
  # return a vector and colSums() would fail.
  min.mods <- min(colSums(mod.data.out[,included.vars,drop=FALSE]))

  if(VI.mods=='min.n'){
    # seq_len() rather than 1:min.mods -- a predictor present in no surviving
    # model gives min.mods of 0, and 1:0 is c(1,0), which would take the single
    # best weight instead of none.
    # first for AICc
    var.weights <- unlist(lapply(included.vars,FUN=function(x){
           sum(sort(mod.data.out$wi.AICc[which(mod.data.out[,x]==1)],decreasing=TRUE)[seq_len(min.mods)])}))
    names(var.weights) <- included.vars
    variable.weights.raw <- var.weights
    aic.var.weights <- list(variable.weights.raw=variable.weights.raw)

    # next for BIC
    var.weights <- unlist(lapply(included.vars,FUN=function(x){
      sum(sort(mod.data.out$wi.BIC[which(mod.data.out[,x]==1)],decreasing=TRUE)[seq_len(min.mods)])}))
    names(var.weights) <- included.vars
    variable.weights.raw <- var.weights
    bic.var.weights <- list(variable.weights.raw=variable.weights.raw)
  }else{
    # else rather than a second if on VI.mods=='all': with two ifs an
    # unrecognised value assigned neither object and the failure surfaced much
    # further down as "object 'aic.var.weights' not found". This function is
    # unexported and only ever reached after fit_model_set()'s match.arg(), so
    # the two branches are exhaustive.
    # first for AICc
    variable.weights.raw <- colSums(mod.data.out[,included.vars,drop=FALSE]*mod.data.out$wi.AICc)
    aic.var.weights <- list(variable.weights.raw=variable.weights.raw)

    # next for BIC
    variable.weights.raw <- colSums(mod.data.out[,included.vars,drop=FALSE]*mod.data.out$wi.BIC)
    bic.var.weights <- list(variable.weights.raw=variable.weights.raw)
  }

  return(list(aic=aic.var.weights,bic=bic.var.weights))
}
