#    Copyright 2020 Australian Institute of Marine Science
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

#' generate_model_set
#'
#' Generate a complete full subsets model set for analysis based on gam(m4) via a call to fit_model_set.
#' @param use.dat A data.frame, with columns matching those included in pred.vars.cont and pred.vars.fact, the response variable to be analysed and any other fields required for the analysis (such as random effects, see test.fit). Note that any variables in use.dat that are used in model fits must not contain missing values, as this invalidates comparison via AICc/ BIC. If missing values occur among the predictor variables the function will return an error warning indicating that these rows need to be removed or interpolated.
#'
#' @param test.fit A gam model fitted via a call to gam (mgcv) or uGamm (MuMIn). This can use any of the (preferably continuous) predictors in the call and will be used as a model to update in the fitting of the model set.
#' The test fit must contain the appropriate random effects and call to family (if not gaussian) and if gamm4 should be used, or gamm in the case of a uGamm call (see ?uGamm).
#' Both gamm from mgcv and gamm4 have slightly different features, as well as advantages and disadvantages, thus it is important that the full subsets function is able to deal with test.fit models based on either package.
#' For example gamm4 is based on the lme4 package [Bates, D.M. (2010) lme4: Mixed-Effects Modeling with R. Springer, New York] which allows crossed random effects and avoids issues with PQL for non-gaussian model fits.
#' On the other hand gamm (mgcv) is based on nlme which allows correlation structures [Box, G.E.P., Jenkins, G.M., and Reinsel G.C. (1994) "Time Series Analysis: Forecasting and Control", 3rd Edition, Holden-Day],
#' variance structures [Pinheiro, J.C. and Bates., D.M. (1996) "Unconstrained Parametrizations for Variance-Covariance Matrices", Statistics and Computing, 6, 289-296],
#' and a broader range of families that are not yet available in lmer (see ?family.mgcv).
#' Models that have no random effects and are based only on gam (mgcv) are best fit via a direct call to gam, rather than using the uGamm wrapper.
#'
#' @param pred.vars.cont A character vector indicating the continuous predictors to use. By default all continuous predictors will be fitted using a smoother (but see argument linear.vars). These must match column names in use.dat exactly. If NA is used the function can be run without any smooth predictors.
#'
#' @param pred.vars.fact A character vector indicating the factor predictors to use. These must match column names in use.dat exactly. If NA is used the function can be run without any factor predictors.
#'
#' @param factor.factor.interactions A logical value indicating if interactions between factors should be included, or only their main effects. Defaults to FALSE. Note that this can substantially increase the number of models in the candidate set. Not recommended when there are factors with many levels. Alternatively character vector specifying which factor predictors to include as interactions. These must be contained within pred.vars.fact.
#' If factor.factor.interactions is set to TRUE the function automatically generates hard coded interaction variables up to the maximum number of predictors (see max.predictors below) using combn. New factors are generated by pasting the resulting unique combinations together. This method of generating interaction terms is necessary because smooth-factor interactions are specified as by arguments in calls to gam(m4). Because the full subsets function automatically checks for collinearity, there is no issue with constructing model sets with multiple factor arguments that are higher order factors of each other, as these are invariably collinear and subsequently removed (see cov.cutoff below). A user defined cor.matrix (see cor.matrix) need not include these hard coded interactions: rows and columns for any it does not name are computed from use.dat.
#'
#' @param smooth.smooth.interactions A logical value indicating if the function should include te smooths of second order continuous predictor interactions. If set to TRUE, all continuous predictors will be combined as bivariate calls to te. Alternatively character vector specifying which continuous predictors to include. These must be contained within pred.vars.cont.
#'
#' @param factor.smooth.interactions Default is the character vector pred.vars.fact, meaning that all factor predictors will be included as by arguments with all the continuous predictors. If factor.factor.interactions is TRUE, factor interactions variables will also be included as by arguments, yielding higher order interactions up to the specified model max.predictors. If a character vector is supplied, this must specify which factor variables should be included as "by" argument interaction terms with the continuous smooth predictors. If a list is supplied, this must be a named list containing the elements fact.vars, linear.vars, cont.vars, each a character vector indicating what predictors should be used to construct the factor smooth interactions. Note that specified factors, linear predictors and continuous predictors must also be included in their respective character vectors (pred.vars.fact, linear.vars, pred.vars.cont). If specified as NA no factor-continuous predictor interactions will be included.
#'
#' @param  max.predictors An integer indicating the maximum number of predictors to include in any one model.
#'
#' @param  cov.cutoff A numeric value between 0 and 1 indicating the correlation cutoff value to use for excluding collinear models, based on the cor.matrix (see below). The default value is 0.28 (see Graham MH (2003). It is highly recommended to keep this value low, as correlation among predictors can yield spurious results. Note that predictors with a correlation greater than the specified value will still appear in the model set but will never appear in the same model. Including highly correlated predictors can make interpreting variable importance values difficult.
#'
#' @param cor.matrix  A user-supplied pairwise correlation matrix, or NA (the default) to compute one from use.dat. When supplied it governs every stage that screens on correlation: which factor-factor interaction columns are built, which te smooth-smooth interaction terms are built, and which assembled candidate models are excluded. It must therefore carry a row and a column for every predictor named in pred.vars.cont, pred.vars.fact and linear.vars; any that are missing are reported by name. The hard coded factor interaction columns that setting factor.factor.interactions causes to be created are the exception, because which of them exist depends on the supplied matrix itself and so cannot be known in advance. Rows and columns for any of those the matrix does not carry are computed from use.dat and appended, leaving every supplied value as supplied. Computing them reads the data of every predictor, so this is the one case in which a predictor of a class check_correlations cannot classify has to be named in the supplied matrix along with the interaction columns. When supplied it replaces the automatic estimate rather than overriding it: except in the interaction case above, check_correlations is not called at all, and a predictor of a class it does not accept can be used. By default predictor correlations are evaluated via a call to check_correlations, a function taking a data.frame (containing all predictors) as argument and generating a correlation matrix comprised of: 1) correlation coefficients between all continuous predictors via a call to cor; 2) approximate correlation values between continuous predictors and factors, as the square root of the R2 value obtained via a call to lm, where the continuous predictor is modelled as a response and the factor variable as a single fixed factor; and 3) approximate correlations values between factor predictors, as the square root of the R2 value obtained via a call multinom (from package nnet, Venables & Ripley 2002). Note that any user constructed pairwise matrix can be passed to the function and used for pairwise exclusion of variables from individual models.
#'
#' @param non.linear.correlations Set this argument to TRUE if you would like to exclude continuous predictor combinations that are potentially "correlated" through non-linear relationships. See ?check_non_linear_correlations for more details.
#'
#' @param k An integer indicating the dimension of the basis used to represent the smooth term (see ?s). The default value is 5. Higher values are not recommended unless a complex trend between the response variable and the continuous predictor variables is expected, and the data are sufficient to support this. k can be reduced to as low as 3 where there is trouble obtaining convergence, or sample size is low. Note that this must be set to override the default value, regardless of what k is used in the test.fit
#'
#' @param bs.arg Specification of the smoother to use, see ?s for more information on smoother provided in gam (mgcv). Note that all continuous predictors specified in pred.vars.cont will be fitted using the same smooth, unless they are also specified as linear.terms or cyclic.vars. Note that any specification of bs in test.fit is discarded.
#'
#' @param cyclic.vars NA if there are no cyclic predictors, or if there are cyclic predictors, a character vector containing the names of any of the continuous predictors that should be modelled as cyclic variables. Note that these must also be contained in the pred.vars.cont character vector. Please also note there are issues with bs='cc' and model selection as this uses by default shrinkage. With shrinkage, variables are retained in models but with zero edf, which makes interpretation of AICc and BIC confusing. To account for this always select only the most parsimonious model (that with the fewest parameters), not just that with the lowest AICc. Reported estimated degrees of freedom (edf) in the model output table represent the sum of the edf of the smooth terms plus the number of parametric coefficients. When cyclic variables are included and shrinkage is used, any estimated edf of the smooth terms that are less than 1 are reset to 1 before summing to ensure the the total number of predictors in the model is captured properly.
#'
#' @param linear.vars NA if there are no continuous predictors to be treated as linear (not fitted as smooths). Only use this where variables are clearly continuous in nature, but you are confident a linear relationship is valid. It may also be useful for continuous predictors that are not well distributed along the x-axis (ie, sampling was conducted in clumped distances from a feature of interest). Where this is necessary, transformations should be considered where they can be used to theoretically linearize response relationships. Does not need to be contained in vector pred.vars.cont
#'
#' @param null.terms A character vector indicating the form of any re smooths to be included in gam
#' [e.g. s(site,bs=re)] or any other fixed terms or smooths that the user wants to include in
#' the null model. Use of bs=re is an alternative way of fitting simple random structures that
#' avoids use of PQL and allows a the greater range of families available in gam.mgcv to be used.
#' see ?s and links therein. Note: make sure you use gam instead of uGamm to make sure PQL is not used.
#' to fit a correlation structure only (but no random effects) this must be achieved through a call the gamm
#' via , with no random effects, fitted
#'
#' @details The function constructs a complete model set based on the supplied arguments.
#' for more information see Fisher R, Wilson SK, Sin TM, Lee AC, Langlois TJ (2018) A simple function for full-subsets multiple regression in ecology with R. Ecology and Evolution
#' https://onlinelibrary.wiley.com/doi/abs/10.1002/ece3.4134
#' @export
#' @return A list of the following output files:
#'
#' n.mods - The number of candidate models generated, equal to length(mod.formula).
#'
#' predictor.correlations - The matrix of estimated predictor correlations returned by the function check_correlations and used for model exclusion based on cov.cutoff
#'
#' mod.formula - A named list containing the model formula that were generated (and will be fitted by fit_model_set). The names are the candidate model names used in the modname column of fit_model_set's output.
#'
#' used.data - A data.frame which is identical to the data.frame initially supplied by the user, but with any hard coded interaction terms appended via cbind.
#'
#' test.fit - The test.fit supplied by the user, passed through so that fit_model_set can update it.
#'
#' included.vars - A character vector of the predictors included in the model set, used to build the variable inclusion columns of fit_model_set's output.
#' @examples
#' library(mgcv)
#' data(case_study1)
#' use.dat <- case_study1
#' use.dat$site <- as.factor(use.dat$site)
#' test.fit <- gam(Herbivore.abundance ~ s(depth, k = 3, bs = "cr") + s(site, bs = "re"),
#'                  family = tw(), data = use.dat)
#' model.set <- generate_model_set(
#'   use.dat = use.dat,
#'   test.fit = test.fit,
#'   pred.vars.cont = c("complexity", "depth"),
#'   pred.vars.fact = "ZONE",
#'   null.terms = "s(site,bs='re')",
#'   max.predictors = 2,
#'   k = 3
#' )
generate_model_set=function(use.dat,
                          test.fit,
                          pred.vars.cont=NA,
                          pred.vars.fact=NA,
                          cyclic.vars=NA,
                          linear.vars=NA,
                          factor.smooth.interactions=pred.vars.fact,
                          factor.factor.interactions=FALSE,
                          smooth.smooth.interactions=FALSE,
                          cov.cutoff=0.28,
                          cor.matrix=NA,
                          non.linear.correlations=FALSE,
                          max.predictors=3,
                          k=5,
                          bs.arg="'cr'",
                          null.terms=""){

  validate_use_dat(use.dat)
  validate_null_terms(null.terms)

  all.predictors=unique(stats::na.omit(c(pred.vars.cont,pred.vars.fact,linear.vars)))
  included.vars=all.predictors

  null.fit.l=build_null_model(test.fit=test.fit,use.dat=use.dat,null.terms=null.terms)
  null.formula=null.fit.l$null.formula

  check_predictor_missingness(use.dat=use.dat,all.predictors=all.predictors)

  factors.l=resolve_factor_interactions(use.dat=use.dat,
                          pred.vars.fact=pred.vars.fact,
                          factor.factor.interactions=factor.factor.interactions,
                          factor.smooth.interactions=factor.smooth.interactions,
                          pred.vars.cont=pred.vars.cont,
                          linear.vars=linear.vars,
                          all.predictors=all.predictors,
                          max.predictors=max.predictors,
                          cov.cutoff=cov.cutoff,
                          cor.matrix=cor.matrix)
  use.dat=factors.l$use.dat
  pred.vars.fact=factors.l$pred.vars.fact
  interaction.terms=factors.l$interaction.terms
  linear.interaction.terms=factors.l$linear.interaction.terms

  # The correlation matrix is resolved before the te() terms are chosen, not
  # after, so that one matrix governs every stage that screens on correlation
  # (FSSgam_package#13). resolve_smooth_smooth_interactions() used to compute
  # its own from use.dat and ignore a supplied cor.matrix entirely, so a user
  # who supplied a matrix saying two predictors were uncorrelated still found
  # their te() term absent.
  #
  # The reorder is safe because this needs all.predictors including the
  # factor-interaction columns, which resolve_factor_interactions() has already
  # created, and does not need the te() term names: those are split into their
  # components before the matrix is indexed.
  all.predictors=stats::na.omit(unique(c(all.predictors,pred.vars.fact)))
  cor.matrix=build_predictor_correlation_matrix(use.dat=use.dat,
                          all.predictors=all.predictors,
                          non.linear.correlations=non.linear.correlations,
                          cor.matrix=cor.matrix,
                          derived.predictors=factors.l$factor.interaction.terms)

  smooth.smooth.interaction.terms=resolve_smooth_smooth_interactions(
                          pred.vars.cont=pred.vars.cont,
                          smooth.smooth.interactions=smooth.smooth.interactions,
                          cov.cutoff=cov.cutoff,
                          max.predictors=max.predictors,
                          cor.matrix=cor.matrix)

  use.mods=enumerate_candidate_models(pred.vars.cont=pred.vars.cont,
                          pred.vars.fact=pred.vars.fact,
                          linear.vars=linear.vars,
                          interaction.terms=interaction.terms,
                          linear.interaction.terms=linear.interaction.terms,
                          smooth.smooth.interaction.terms=smooth.smooth.interaction.terms,
                          max.predictors=max.predictors,
                          cor.matrix=cor.matrix,
                          cov.cutoff=cov.cutoff)

  mod.formula=build_model_formulas(use.mods=use.mods,
                          pred.vars.cont=pred.vars.cont,
                          pred.vars.fact=pred.vars.fact,
                          linear.vars=linear.vars,
                          linear.interaction.terms=linear.interaction.terms,
                          cyclic.vars=cyclic.vars,
                          k=k,
                          bs.arg=bs.arg,
                          null.terms=null.terms,
                          null.formula=null.formula,
                          test.fit=test.fit)

  # Is this too many models?
  n.mods=length(mod.formula)
  return(list(n.mods=n.mods,
              predictor.correlations=cor.matrix,
              mod.formula=mod.formula,
              used.data=use.dat,
              test.fit=test.fit,
              included.vars=included.vars))
} #------------------ end function --------------------------------------------#

# Internal helpers for generate_model_set(). Not exported.

# Confirms use.dat is a data.frame (not e.g. a tibble).
validate_use_dat=function(use.dat){
  # identical() rather than inherits(): this rejects a tibble or a data.table
  # deliberately, and inherits(x,"data.frame") accepts both.
  if(!identical(class(use.dat),"data.frame")){
    stop("use.dat must be a data.frame, perhaps you have a tibble? FSSgam does not currently support tibbles.")
  }
}

# Confirms null.terms is a single, non-missing character string (possibly "").
# Without this check, downstream nchar(null.terms) calls fail in confusing,
# type-dependent ways (e.g. NA errors "missing value where TRUE/FALSE needed",
# a length>1 vector errors "the condition has length > 1", and a bare numeric
# or logical value is silently accepted and spliced into a nonsense formula).
validate_null_terms=function(null.terms){
  if(!is.character(null.terms) || length(null.terms)!=1 || is.na(null.terms)){
    stop("null.terms must be a single character string (e.g. \"s(site,bs='re')\"), or \"\" if no null term is required.")
  }
}

# Builds the null model formula and confirms test.fit can be updated to it.
# Returns list(null.formula=, null.fit=).
build_null_model=function(test.fit,use.dat,null.terms){
  if(nchar(null.terms)>0){
    null.formula=stats::as.formula(paste("~ ",null.terms,sep=""))}else{
    null.formula=stats::as.formula("~ 1")}

  if(length(grep("dsm",class(test.fit)))>0){
    null.fit=try(stats::update(test.fit,formula=null.formula),silent=TRUE)
  }else{
    # family= is intentionally omitted here, same reasoning as fit_mod_l()
    # in functions_supporting.R (see its comment) -- do not "fix" this by
    # adding family=stats::family(test.fit) back in.
    null.fit=try(stats::update(test.fit,formula=null.formula,data=use.dat),silent=TRUE)}

  if(inherits(null.fit,"try-error")){
        stop(paste("Null model not successfully fitted, please check your inputs.
                   If there are no random effects try using 'gam' instead of 'uGamm'
                   in your test.fit model call.",
                   " ",
                   "The following error message was provided:  ",
                   "  ",
                   null.fit, ""))}

  return(list(null.formula=null.formula,null.fit=null.fit))
}

# Stops if any predictor column contains missing values.
check_predictor_missingness=function(use.dat,all.predictors){
  if(anyNA(use.dat[,all.predictors])){
        stop("Predictor variables contain NA and AICc/BIC comparisons are invalid.
        Remove rows with NA from the input data or interpolate missing predictors.")}
}

# Builds hard-coded factor-factor interaction columns (if requested), coerces
# all factor predictors to class factor, and resolves the factor-smooth (.by.
# / .t.) interaction term names. Returns list(use.dat=, pred.vars.fact=,
# interaction.terms=, linear.interaction.terms=).
# The combination sizes to enumerate: every size from 2 up to max.size, capped
# at the number of variables available.
#
# The explicit empty case is the fix for a defect. This was written as
# `for(i in 2:n)`, and at n = 1 that sequence counts backwards to c(2, 1), so a
# size-1 "combination" was enumerated as well. Its pasted name is just the
# original variable name, so cbind() appended a duplicate column, and taking
# max() of the empty off-diagonal of a 1x1 sub-matrix warned "no non-missing
# arguments to max; returning -Inf" once per variable.
#
# n is min(max.size, length(vars)), so 2:n can never exceed the number of
# variables and needs no further filtering.
combination_sizes=function(vars,max.size){
  n=min(max.size,length(vars))
  if(n<2){return(integer(0))}
  2:n
}

# Every combination of `vars` at each size in `sizes`, dropping any whose
# sub-matrix of `cor.matrix` exceeds `cov.cutoff` off the diagonal. Returns a
# list of character vectors, possibly empty.
#
# Both triangles are screened, not just the upper one. The correlation
# matrices this is given are not necessarily symmetric: check_correlations()
# estimates a factor-factor value by fitting multinom() separately in each
# direction, and check_non_linear_correlations() is asymmetric by construction,
# its rows being responses and its columns predictors. Screening the upper
# triangle alone therefore accepted a pair whose correlation exceeded the
# cutoff in the other direction. Three of the four callers used to do exactly
# that.
#
# The `if (max(...) > cov.cutoff) out <- NA` shape is kept rather than reduced
# to a logical vector: max() of an all-NA sub-matrix returns NA, and `if (NA)`
# raises an error, which is the existing behaviour. A vapply() over a logical
# predicate would silently drop the combination instead.
combine_uncorrelated=function(vars,sizes,cor.matrix,cov.cutoff){
  combns=list()
  for(i in sizes){
    combns=c(combns,utils::combn(vars,i,simplify=FALSE))}
  combns=lapply(combns,FUN=function(x){
          row.index=which(match(rownames(cor.matrix),x)>0)
          col.index=which(match(colnames(cor.matrix),x)>0)
          cor.mat.m=cor.matrix[row.index,col.index]
          out=x
          if(max(abs(cor.mat.m[upper.tri(cor.mat.m)]))>cov.cutoff){out=NA}
          if(max(abs(cor.mat.m[lower.tri(cor.mat.m)]))>cov.cutoff){out=NA}
          return(out)})
  combns[which(is.na(combns))]=NULL
  combns
}

# Pastes each surviving combination of factors into a new column named a.I.b
# and appends them to use.dat. Returns the extended data and the new names.
#
# Nothing is appended when there are no combinations. Reaching cbind() with a
# zero-column data.frame raises "arguments imply differing number of rows",
# which is what the character factor.factor.interactions branch used to do; the
# logical branch guarded against it. Warning about an empty result is left to
# the callers, which are the only place that can tell the two reasons for it
# apart.
build_factor_interaction_columns=function(use.dat,fact.combns){
  factor.interaction.terms=unlist(lapply(fact.combns,FUN=paste,collapse=".I."))

  if(length(fact.combns)>0){
    tt=data.frame(lapply(fact.combns,FUN=function(x){
               do.call("paste",as.list(use.dat[,x]))}))
    colnames(tt)=factor.interaction.terms
    use.dat=cbind(use.dat,tt)}

  list(use.dat=use.dat,factor.interaction.terms=factor.interaction.terms)
}

# The warning for a collinearity screen that left nothing. Shared so the two
# factor.factor.interactions branches cannot drift apart again: the character
# branch used to be silent here.
warn_no_factor_interactions=function(cov.cutoff){
  warning(paste0("No factor-factor interaction terms were generated: every
                combination of the specified factors exceeded cov.cutoff (",
                cov.cutoff,")."))
}

# Normalises factor.smooth.interactions to one triple of variable sets.
#
# The character form names only the factors, and the continuous and linear
# predictors are taken from pred.vars.cont and linear.vars. The list form names
# all three itself, and is validated against all.predictors first -- a check
# the character form does not make, because pred.vars.fact has already been
# validated by the time it is reached.
normalise_factor_smooth_interactions=function(factor.smooth.interactions,
                          pred.vars.cont,linear.vars,all.predictors){
  if(inherits(factor.smooth.interactions,"list")){
    check.list=match(stats::na.omit(
    unlist(factor.smooth.interactions)),all.predictors)

    if(length(which(is.na(check.list)))>0){
            stop(paste("Variable(s)",
                       unlist(factor.smooth.interactions)[which(is.na(check.list))] ,
                       "included in the factor.smooth.interactions list do(es)
                       not appear in either pred.vars.fact, pred.vars.cont or linear.vars.
                       Please ensure all predictors are specified as one of these three types"))}

    return(list(fact.vars=factor.smooth.interactions$fact.vars,
                cont.vars=factor.smooth.interactions$cont.vars,
                linear.vars=factor.smooth.interactions$linear.vars))
  }
  list(fact.vars=factor.smooth.interactions,
       cont.vars=pred.vars.cont,
       linear.vars=linear.vars)
}

# Builds the ".by." and ".t." interaction term names from that triple.
#
# The requested factors are first expanded to include any hard-coded ".I."
# interaction column built from them, so naming a factor also brings in the
# interactions it participates in.
build_factor_smooth_terms=function(spec,pred.vars.fact){
  interaction.terms=NA
  linear.interaction.terms=NA

  # a hard coded ".I." interaction is included when every factor it was built
  # from was named
  fact.vars=pred.vars.fact[!vapply(strsplit(pred.vars.fact,split=".I.",fixed=TRUE),
     function(x){anyNA(match(x,spec$fact.vars))},logical(1))]

  if(length(stats::na.omit(fact.vars))>0){
   # pred.vars.cont=NA is a documented way to run without smooth predictors.
   # Without this guard expand.grid() pairs the NA itself with each factor,
   # producing a phantom "NA.by.<factor>" term. At max.predictors=1 that term
   # is discarded again before the model set is returned, and the only symptom
   # is enumerate_candidate_models() taking max() of an empty correlation
   # sub-matrix and warning; from max.predictors=2 it survives into the
   # candidate set as a model whose formula smooths the literal NA.
   if(length(stats::na.omit(spec$cont.vars))>0){
    all.interactions=expand.grid(spec$cont.vars,fact.vars)
    interaction.terms=paste(all.interactions$Var1,all.interactions$Var2,sep=".by.")}

   # now interactions between linear continous predictors and factors
   if(length(stats::na.omit(spec$linear.vars))>0){
    linear.interactions=expand.grid(spec$linear.vars,fact.vars)
    linear.interaction.terms=paste(linear.interactions$Var1,linear.interactions$Var2,
                               sep=".t.")}
   }

  list(interaction.terms=interaction.terms,
       linear.interaction.terms=linear.interaction.terms)
}

# cor.matrix here is the raw user-supplied matrix, or NA, not the resolved one.
# The resolved matrix is built over all.predictors, which includes the
# interaction columns this function creates, so it cannot exist yet
# (FSSgam_package#13).
resolve_factor_interactions=function(use.dat,pred.vars.fact,factor.factor.interactions,
                          factor.smooth.interactions,pred.vars.cont,linear.vars,
                          all.predictors,max.predictors,cov.cutoff,cor.matrix){
  factor_correlations=function(vars){
    if(length(cor.matrix)==1){
      check_correlations(use.dat[,vars])
    }else{
      missing.vars=vars[which(is.na(match(vars,rownames(cor.matrix))))]
      if(length(missing.vars)>0){
        stop(paste("Supplied cor.matrix is missing required predictors: ",
             paste(missing.vars,collapse=", "),".",sep=""))}
      cor.matrix[vars,vars,drop=FALSE]}
  }
  interaction.terms=NA
  linear.interaction.terms=NA
  # The names of the hard coded interaction columns this function appends to
  # use.dat. Returned so that build_predictor_correlation_matrix() can tell a
  # predictor the user could have named from one this function invented
  # (FSSgam_package#15).
  factor.interaction.terms=character(0)

  # if there are factors
  if(length(stats::na.omit(pred.vars.fact))>0){
  # if there are two or more factors
  if(length(stats::na.omit(pred.vars.fact))>1){
    # make all the interactions between factors
    if(inherits(factor.factor.interactions,"logical")){
     if(factor.factor.interactions==TRUE){
        if(length(pred.vars.fact)<2){
            stop("You have less than 2 factors. Please reset 'factor.factor.interactions' to 'False'")}
      factor.correlations=factor_correlations(pred.vars.fact)
      # Two different reasons for building nothing, which need different
      # messages: max.predictors leaves no room for an interaction of two or
      # more factors, or combinations were enumerated and every one exceeded
      # cov.cutoff. warn.when.empty covers the second; the first is reported
      # here, because only this point knows max.predictors.
      fact.sizes=combination_sizes(pred.vars.fact,max.predictors)
      if(length(fact.sizes)==0){
        warning(paste0("factor.factor.interactions is TRUE but max.predictors is ",
                max.predictors,", so no interaction of two or more factors can be
                included. No factor-factor interaction terms were generated."))}
      fact.combns=combine_uncorrelated(vars=pred.vars.fact,
                          sizes=fact.sizes,
                          cor.matrix=factor.correlations,cov.cutoff=cov.cutoff)
      if(length(fact.sizes)>0 & length(fact.combns)==0){
        warn_no_factor_interactions(cov.cutoff)}
      cols.l=build_factor_interaction_columns(use.dat=use.dat,fact.combns=fact.combns)
      use.dat=cols.l$use.dat
      factor.interaction.terms=c(factor.interaction.terms,cols.l$factor.interaction.terms)
      pred.vars.fact=c(pred.vars.fact,cols.l$factor.interaction.terms)
      }
    }
    # make only specified interactions between factors
    if(inherits(factor.factor.interactions,"character")){
        if(length(factor.factor.interactions)<2){
            stop("You specified less than 2 factors as factor.factor.interactions.")}
        if(anyNA(match(factor.factor.interactions,colnames(use.dat)))){
            stop("Not all specified factor.factor.interactions are supplied in use.dat")}
      factor.correlations=factor_correlations(factor.factor.interactions)
      # An outer guard here, if(length(which(factor.correlations<cov.cutoff))>1),
      # used to skip this whole block in silence. It counted cells of the
      # correlation matrix below the cutoff rather than pairs, so two factors
      # whose two off-diagonal estimates straddle cov.cutoff gave a count of 1
      # and no interaction was built and nothing was reported. The logical
      # branch had no such guard. Removed: combine_uncorrelated() already
      # rejects a combination that exceeds the cutoff, and an empty result is
      # now warned about below.
      fact.sizes=combination_sizes(factor.factor.interactions,max.predictors)
      if(length(fact.sizes)==0){
        warning(paste0("max.predictors is ",max.predictors,", so no interaction of
                two or more of the specified factors can be included. No
                factor-factor interaction terms were generated."))}
      fact.combns=combine_uncorrelated(vars=factor.factor.interactions,
                          sizes=fact.sizes,
                          cor.matrix=factor.correlations,cov.cutoff=cov.cutoff)
      if(length(fact.sizes)>0 & length(fact.combns)==0){
        warn_no_factor_interactions(cov.cutoff)}
      cols.l=build_factor_interaction_columns(use.dat=use.dat,fact.combns=fact.combns)
      use.dat=cols.l$use.dat
      factor.interaction.terms=c(factor.interaction.terms,cols.l$factor.interaction.terms)
      pred.vars.fact=c(pred.vars.fact,cols.l$factor.interaction.terms)
    }
   }
   # make sure the factors are factors
   for(f in seq_along(pred.vars.fact)){
       use.dat[,pred.vars.fact[f]]=factor(use.dat[,pred.vars.fact[f]])}


   # check which factors should be included as interactions with the smoothers
   #
   # The character and list forms differ only in where the three variable sets
   # come from, so they are normalised to one triple and then handled once.
   # factor.smooth.interactions=NA is neither, and correctly falls through with
   # interaction.terms left at NA.
   if(inherits(factor.smooth.interactions,"character")|
      inherits(factor.smooth.interactions,"list")){
     spec=normalise_factor_smooth_interactions(
                          factor.smooth.interactions=factor.smooth.interactions,
                          pred.vars.cont=pred.vars.cont,linear.vars=linear.vars,
                          all.predictors=all.predictors)
     smooth.terms.l=build_factor_smooth_terms(spec=spec,pred.vars.fact=pred.vars.fact)
     interaction.terms=smooth.terms.l$interaction.terms
     linear.interaction.terms=smooth.terms.l$linear.interaction.terms
   }

   }

  return(list(use.dat=use.dat,
              pred.vars.fact=pred.vars.fact,
              factor.interaction.terms=factor.interaction.terms,
              interaction.terms=interaction.terms,
              linear.interaction.terms=linear.interaction.terms))
}

# Builds the names of the te() smooth-smooth interaction terms to consider,
# excluding any continuous-predictor pairs that exceed cov.cutoff. Returns a
# character vector (or NA if smooth.smooth.interactions is not requested).
resolve_smooth_smooth_interactions=function(pred.vars.cont,smooth.smooth.interactions,
                          cov.cutoff,max.predictors,cor.matrix){
   smooth.smooth.interaction.terms=NA
    # for interactions amongst all continuous predictors
    if(inherits(smooth.smooth.interactions,"logical")){
      if(smooth.smooth.interactions==TRUE){
        if(length(pred.vars.cont)<2){
            stop("You have less than 2 continuous predictors you wish interactions for.
            Please reset 'smooth.smooth.interactions' to 'False'")}
       # Subset of the matrix the caller resolved, rather than a fresh one
       # computed from use.dat. When no cor.matrix was supplied the two agree:
       # the continuous-continuous block does not depend on which other
       # predictors are present, checked against both check_correlations() and
       # check_non_linear_correlations() with a maximum absolute difference of
       # 0. When one was supplied, it now governs here too
       # (FSSgam_package#13).
       continuous.correlations=cor.matrix[pred.vars.cont,pred.vars.cont,drop=FALSE]

      # The size is fixed at 2 here while the character branch below goes up to
      # max.predictors. That difference is intentional, not an unfinished edit:
      # smooth.smooth.interactions = TRUE builds bivariate te() terms, and a
      # character vector builds terms of every size from 2 to max.predictors,
      # so te(a, b, c) is reachable only through the character form. The
      # documentation states both forms separately.
      #
      # combination_sizes(pred.vars.cont, 2) is 2 exactly, because the guard
      # above has already rejected fewer than two continuous predictors.
      cont.combns=combine_uncorrelated(vars=pred.vars.cont,
                          sizes=combination_sizes(pred.vars.cont,2),
                          cor.matrix=continuous.correlations,cov.cutoff=cov.cutoff)
      smooth.smooth.interaction.terms=unlist(lapply(cont.combns,FUN=paste,collapse=".te."))
     }
    }
    # for only specific interactions amongst continuous predictors
    if(inherits(smooth.smooth.interactions,"character")){
        if(length(smooth.smooth.interactions)<2){
            stop("You specified less than 2 variables as smooth.smooth.interactions.")}
        # Checked against the resolved correlation matrix, which is built over
        # the predictors, not against colnames(use.dat) as it used to be. A
        # column of use.dat that is not a predictor has no row in the matrix,
        # so it cannot be screened; it previously reached combine_uncorrelated()
        # with an empty sub-matrix and was admitted on a max() of nothing. The
        # message names the real requirement rather than repeating the old one.
        missing.cont=smooth.smooth.interactions[
                          which(is.na(match(smooth.smooth.interactions,rownames(cor.matrix))))]
        if(length(missing.cont)>0){
            stop(paste("Variable(s) ",paste(missing.cont,collapse=", "),
                 " named in smooth.smooth.interactions are not predictors. Each must",
                 " appear in pred.vars.cont (or linear.vars).",sep=""))}
      # see the matching comment in the logical branch above
      continuous.correlations=cor.matrix[smooth.smooth.interactions,
                                         smooth.smooth.interactions,drop=FALSE]

      cont.combns=combine_uncorrelated(vars=smooth.smooth.interactions,
                          sizes=combination_sizes(smooth.smooth.interactions,max.predictors),
                          cor.matrix=continuous.correlations,cov.cutoff=cov.cutoff)
      smooth.smooth.interaction.terms=unlist(lapply(cont.combns,FUN=paste,collapse=".te."))
    }

  return(smooth.smooth.interaction.terms)
}

# Resolves the predictor correlation matrix used for collinearity-based
# model exclusion: either computed from use.dat, or validated if the caller
# supplied their own cor.matrix.
build_predictor_correlation_matrix=function(use.dat,all.predictors,non.linear.correlations,
                          cor.matrix,derived.predictors=character(0)){
  if(length(cor.matrix)==1){
   # Computed only when the caller supplied nothing. It used to be computed
   # either way and then discarded in the else branch below, which meant a
   # supplied cor.matrix did not actually replace the automatic estimate: the
   # multinom() and gam() fits still ran, and a predictor of a class
   # check_correlations() rejects (a Date, say) still aborted the call even
   # though its correlations had been supplied. Nothing else in the function
   # reads it (FSSgam_package#13).
   #
   # drop=FALSE matters: with a single predictor use.dat[,all.predictors] would
   # otherwise collapse to a bare vector, and both check_* functions require a
   # data.frame (they classify columns via sapply(dat,class) and compare against
   # ncol(dat)). Without it, any model set with exactly one predictor failed
   # with an unrelated "argument is of length zero" error.
   if(non.linear.correlations==TRUE){
    cor.matrix=check_non_linear_correlations(use.dat[,all.predictors,drop=FALSE])}else{
    cor.matrix=check_correlations(use.dat[,all.predictors,drop=FALSE])}
   # Replace NA and NaN with zero. is.na() is TRUE for NaN as well, so this is
   # one pass rather than two; the NaN pass was written as
   # which(cor.matrix == "NaN"), which coerces the matrix to character and
   # happens to work.
   cor.matrix[is.na(cor.matrix)]=0}else{
      # check if the user defined matrix has the same rownames and colnames
      check.predictors=c(match(all.predictors,colnames(cor.matrix)),
                         match(all.predictors,rownames(cor.matrix)))
      missing.predictors=unique(rep(all.predictors,2)[which(is.na(check.predictors))])

      # A predictor the user named and did not supply is still an error, so a
      # misspelled name is reported rather than quietly computed. A hard coded
      # factor interaction column is not: its name is invented by
      # resolve_factor_interactions() from the combinations that survive the
      # screen, which itself depends on the supplied matrix, so a user cannot
      # know in advance which of them to supply (FSSgam_package#15). Those rows
      # and columns are computed from use.dat instead.
      derived.missing=intersect(missing.predictors,derived.predictors)
      named.missing=setdiff(missing.predictors,derived.predictors)
      if(length(named.missing)>0){
            stop(paste("Supplied cor.matrix is missing required predictors: ",
            paste(named.missing,collapse=", "),".",sep=""))}
      if(length(derived.missing)>0){
        cor.matrix=augment_supplied_correlation_matrix(use.dat=use.dat,
                          cor.matrix=cor.matrix,
                          derived.missing=derived.missing,
                          all.predictors=all.predictors,
                          non.linear.correlations=non.linear.correlations)}
  }
  return(cor.matrix)
}

# Extends a supplied cor.matrix with rows and columns for the hard coded factor
# interaction columns the user could not have named (FSSgam_package#15).
#
# Every cell the user supplied is kept as supplied; only cells involving a
# derived column are computed. The computation needs the other predictors' data,
# so a predictor of a class check_correlations() rejects can no longer be used
# together with factor.factor.interactions and a supplied matrix. That is
# reported as such rather than as the class error on its own, since the caller
# has already supplied correlations for it.
#
# The supplied names are kept in their own order and the derived ones appended,
# rows and columns separately, so a matrix whose two dimnames differ is not
# reshaped into a square one with an invented all-NA row.
#
# A name the supplied matrix carries that is not a predictor of this model set
# has no computed value against a derived column. Those cells are set to zero,
# not left NA, which is what the branch that computes the whole matrix already
# does with the NA values check_correlations() returns. Leaving them NA is not
# safe: the character form of smooth.smooth.interactions validates its argument
# against the rownames of the resolved matrix rather than against the
# predictors, so such a name can reach combine_uncorrelated(), where max() of an
# all-NA sub-matrix returns NA and `if (NA)` raises an error naming neither the
# matrix nor the argument.
augment_supplied_correlation_matrix=function(use.dat,cor.matrix,derived.missing,
                          all.predictors,non.linear.correlations){
  computed=try(if(non.linear.correlations==TRUE){
      check_non_linear_correlations(use.dat[,all.predictors,drop=FALSE])
    }else{
      check_correlations(use.dat[,all.predictors,drop=FALSE])},silent=TRUE)
  if(inherits(computed,"try-error")){
    stop(paste0("Supplied cor.matrix does not cover the hard coded factor ",
         "interaction predictor(s) ",paste(derived.missing,collapse=", "),
         ", and correlations for them could not be computed from use.dat: ",
         attr(computed,"condition")$message,
         " Either add rows and columns for them to cor.matrix, or use ",
         "predictors check_correlations can classify."))}
  computed[is.na(computed)]=0

  # as.matrix() because assigning a data.frame into a matrix sub-block replaces
  # the matrix with a plain list, dropping dim and dimnames, and the next
  # assignment then fails on what is no longer a matrix. A data.frame cor.matrix
  # is accepted everywhere else.
  cor.matrix=as.matrix(cor.matrix)
  row.vars=unique(c(rownames(cor.matrix),derived.missing))
  col.vars=unique(c(colnames(cor.matrix),derived.missing))
  out=matrix(NA_real_,nrow=length(row.vars),ncol=length(col.vars),
             dimnames=list(row.vars,col.vars))
  out[rownames(cor.matrix),colnames(cor.matrix)]=cor.matrix
  known.cols=intersect(col.vars,colnames(computed))
  known.rows=intersect(row.vars,rownames(computed))
  out[derived.missing,known.cols]=computed[derived.missing,known.cols,drop=FALSE]
  out[known.rows,derived.missing]=computed[known.rows,derived.missing,drop=FALSE]

  # only the cells this function created; an NA the user supplied among their
  # own predictors is left alone
  new.rows=out[derived.missing,,drop=FALSE]
  new.rows[is.na(new.rows)]=0
  out[derived.missing,]=new.rows
  new.cols=out[,derived.missing,drop=FALSE]
  new.cols[is.na(new.cols)]=0
  out[,derived.missing]=new.cols
  out
}

# Enumerates every combination of available terms up to max.predictors, then
# removes redundant/invalid combinations (collinear above cov.cutoff, "by"
# terms without their main effect, more terms than max.predictors allows, a
# continuous predictor appearing both alone and inside an interaction).
# Returns the deduplicated list of valid term-name vectors.
enumerate_candidate_models=function(pred.vars.cont,pred.vars.fact,linear.vars,
                          interaction.terms,linear.interaction.terms,
                          smooth.smooth.interaction.terms,max.predictors,
                          cor.matrix,cov.cutoff){
  # make all possible combinations
  if(length(stats::na.omit(c(pred.vars.cont,linear.vars,
                      pred.vars.fact)))<max.predictors){
        stop("Model max.predictors is greater than the number of predictors.")}
  all.mods=list()
  for(i in 1:max.predictors){
    all.mods=c(all.mods,
     utils::combn(stats::na.omit(c(pred.vars.cont,pred.vars.fact,
                     linear.vars,
                     interaction.terms,
                     linear.interaction.terms,
                     smooth.smooth.interaction.terms)),
                     i,simplify=FALSE))
  }

  # remove redundant models
  use.mods=all.mods
  for(m in seq_along(all.mods)){
    mod.m=all.mods[[m]]
    mod.terms=unlist(strsplit(unlist(strsplit(unlist(strsplit(mod.m,
                               split=".by.",fixed=TRUE)),
                               split=".t.",fixed=TRUE)),
                               split=".te.",fixed=TRUE))
    n.vars.m=unique(unlist(strsplit(unlist(strsplit(unlist(strsplit(unlist(strsplit(mod.m,
                                  split=".by.",fixed=TRUE)),
                                  split=".I.",fixed=TRUE)),
                                  split=".t.",fixed=TRUE)),
                                  split=".te.",fixed=TRUE)))
    cont.vars=stats::na.omit(stats::na.omit(c(pred.vars.cont,linear.vars))[match(mod.terms,
                                           stats::na.omit(c(pred.vars.cont,linear.vars)))])
    fact.vars=unique(stats::na.omit(pred.vars.fact[match(mod.terms,pred.vars.fact)]))

    # if there are factor vars
    if(length(fact.vars)>0){
      # check that any "by" factor vars are accompanied by a + term in its owns right
      if(anyNA(match(fact.vars,mod.m))){use.mods[[m]]=NA}}

    # remove the model if the predictors are correlated
    if(length(mod.terms)>1){
     row.index=which(match(rownames(cor.matrix),unique(mod.terms))>0)
     col.index=which(match(colnames(cor.matrix),unique(mod.terms))>0)
     cor.mat.m=cor.matrix[row.index,col.index]
     if(max(abs(cor.mat.m[upper.tri(cor.mat.m)]))>cov.cutoff){use.mods[[m]]=NA}
     if(max(abs(cor.mat.m[lower.tri(cor.mat.m)]))>cov.cutoff){use.mods[[m]]=NA}
    }

    # remove the model if there are more than the number of terms specified in "max.predictors"
    if(length(n.vars.m)>max.predictors){use.mods[[m]]=NA}

    # remove the models if a continuous predictor occurs as a by, or a te, and as a single term
    if(length(cont.vars)>length(unique(cont.vars))){use.mods[[m]]=NA}

  }

  use.mods[which(is.na(use.mods))]=NULL

  # method="radix" sorts in byte order regardless of the session's LC_COLLATE.
  # Candidate names are built by sorting term names, so without it the same
  # analysis produced "complexity+ZONE" in an en_US.UTF-8 session and
  # "ZONE+complexity" in a C-locale one, and mod.data.out came back in a
  # different row order (FSSgam_package#8).
  use.mods=unique(lapply(use.mods,FUN=sort,method="radix"))

  return(use.mods)
}

# Converts the deduplicated term-name combinations (use.mods) into actual gam
# formula objects, handling smooth/by/te/linear/factor terms, cyclic.vars,
# and the null model. Returns the named list of formulas (including "null").
build_model_formulas=function(use.mods,pred.vars.cont,pred.vars.fact,linear.vars,
                          linear.interaction.terms,cyclic.vars,k,bs.arg,null.terms,
                          null.formula,test.fit){
  # now make the models into gamm formula
  if(nchar(null.terms)==0){# if there is no bs='re' random effect random effect
                             # or other null term in the null model
    mod.formula=list(stats::as.formula("~ 1"))}
  if(nchar(null.terms)>0){# to add a bs='re' random effect
    mod.formula=list(null.formula)}

  # The smoothing basis for one variable. Applied as each term is built, from
  # the variable name itself.
  #
  # This used to be done afterwards, by rewriting the assembled term strings:
  # grep(cyclic.vars[r], term) matched the name anywhere in the string and
  # treated it as a regular expression, so declaring "depth" cyclic also made
  # "depthx" cyclic, and a name containing "." matched any character. A second
  # block then existed only to repair the te() terms the first had damaged.
  # Both are gone.
  bs_for=function(v){
    if(v %in% stats::na.omit(cyclic.vars)){"'cc'"}else{bs.arg}}

  for(m in seq_along(use.mods)){
     mod.m=use.mods[[m]]
     cont.smooths=mod.m[which(match(mod.m,setdiff(pred.vars.cont,linear.vars))>0)]
     by.smooths=mod.m[grep(".by.",mod.m,fixed=TRUE)]
     te.smooths=mod.m[grep(".te.",mod.m,fixed=TRUE)]
     factor.terms=mod.m[which(match(mod.m,pred.vars.fact)>0)]
     linear.terms=mod.m[which(match(mod.m,linear.vars)>0)]
     # Matched against the .t. term names resolve_factor_interactions() actually
     # generated, the same way factor.terms and linear.terms are matched against
     # their own vectors. Two earlier forms were wrong. Building a pattern as
     # paste(linear.vars,".t.") made it a vector whenever more than one
     # linear.vars was supplied, and grep() then silently used only its first
     # element, so every interaction term belonging to a second or later linear
     # predictor was dropped from the fitted formula while the candidate kept
     # its interaction name. Deriving the prefixes from linear.vars here instead
     # fixed that, but still disagreed with the generator whenever the terms came
     # from factor.smooth.interactions$linear.vars, which is validated against
     # all.predictors rather than against linear.vars -- so the same silent drop
     # reappeared for a list-form factor.smooth.interactions naming a linear
     # predictor absent from linear.vars.
     linear.interaction.terms.m=mod.m[which(match(mod.m,linear.interaction.terms)>0)]
     all.terms.vec=character()

     if(length(cont.smooths)>0){all.terms.vec=c(all.terms.vec,
                  paste("s(",cont.smooths,",k=",k,",bs=",
                        vapply(cont.smooths,bs_for,character(1)),")",sep=""))}
     if(length(by.smooths)>0){
       # the smooth variable is the part before ".by."; the factor after it
       # carries no basis of its own
       all.terms.vec=c(all.terms.vec,
         paste("s(",gsub(".by.",",by=",by.smooths,fixed=TRUE),",k=",k,",bs=",
               vapply(sub("\\.by\\..*$","",by.smooths),bs_for,character(1)),")",sep=""))}
     if(length(te.smooths)>0){
       # one basis per marginal variable, in the order they appear in the name
       bs.vec=vapply(strsplit(te.smooths,".te.",fixed=TRUE),
                     function(v){paste0("bs=c(",
                        paste(vapply(v,bs_for,character(1)),collapse=","),")")},
                     character(1))
       te.fun=if(inherits(test.fit,"gamm4")){"t2("}else{"te("}
       all.terms.vec=c(all.terms.vec,
         paste(te.fun,gsub(".te.",",",te.smooths,fixed=TRUE),",k=",k,",",bs.vec,")",sep=""))}
      if(length(linear.interaction.terms.m)>0){all.terms.vec=c(all.terms.vec,
               gsub(".t.","*",linear.interaction.terms.m,fixed=TRUE))}
     if(length(factor.terms)>0){all.terms.vec=c(all.terms.vec,factor.terms)}
     if(length(linear.terms)>0){all.terms.vec=c(all.terms.vec,linear.terms)}

     if(nchar(null.terms)==0){# if there is no bs='re' random effect
                                # or other null term in the null model
       formula.m=stats::as.formula(paste("~",
               paste(all.terms.vec,collapse="+")))}
     if(nchar(null.terms)>0){#
       formula.m=stats::as.formula(paste("~",
               paste(c(all.terms.vec,null.terms),collapse="+")))}
     mod.formula=c(mod.formula,list(formula.m))
  }

  names(mod.formula)=c("null",lapply(use.mods,FUN=paste,collapse="+"))

  return(mod.formula)
}
