#    Copyright 2020 Australian Institute of Marine Science
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

#' generate_model_set
#'
#' Generate a complete full subsets model set for analysis based on gam(m4) via a call to fit_model_set.
#' @param use.dat A data.frame, with columns matching those included in pred.vars.cont and pred.vars.fact, the response variable to be analysed and any other fields required for the analysis (such as random effects, see test.fit). Note that any variables in use.dat that are used in model fits must not contain missing values, as this invalidates comparison via AICc/ BIC. If missing values occur among the predictor variables the function will return an error warning indicating that these rows need to be removed or interpolated.
#'
#' @param test.fit A gam model fitted via a call to gam (mgcv) or uGamm (MuMIn). This can use any of the (preferably continuous) predictors in the call and will be used as a model to update in the fitting of the model set.
#' The test fit must contain the appropriate random effects and call to family (if not gaussian) and if gamm4 should be used, or gamm in the case of a uGamm call (see ?uGamm).
#' Both gamm from mgcv and gamm4 have slightly different features, as well as advantages and disadvantages, thus it is important that the full subsets function is able to deal with test.fit models based on either package.
#' For example gamm4 is based on the lme4 package [Bates, D.M. (2010) lme4: Mixed-Effects Modeling with R. Springer, New York] which allows crossed random effects and avoids issues with PQL for non-gaussian model fits.
#' On the other hand gamm (mgcv), reached through MuMIn::uGamm since a bare mgcv::gamm fit cannot be refitted, is based on nlme which allows correlation structures [Box, G.E.P., Jenkins, G.M., and Reinsel G.C. (1994) "Time Series Analysis: Forecasting and Control", 3rd Edition, Holden-Day],
#' variance structures [Pinheiro, J.C. and Bates., D.M. (1996) "Unconstrained Parametrizations for Variance-Covariance Matrices", Statistics and Computing, 6, 289-296],
#' and a broader range of families that are not yet available in lmer (see ?family.mgcv).
#' Models that have no random effects and are based only on gam (mgcv) are best fit via a direct call to gam, rather than using the uGamm wrapper.
#'
#' @param pred.vars.cont A character vector indicating the continuous predictors to use. By default all continuous predictors will be fitted using a smoother (but see argument linear.vars). These must match column names in use.dat exactly. If NA is used the function can be run without any smooth predictors.
#'
#' @param pred.vars.fact A character vector indicating the factor predictors to use. These must match column names in use.dat exactly. If NA is used the function can be run without any factor predictors.
#'
#' @param factor.factor.interactions A logical value indicating if interactions between factors should be included, or only their main effects. Defaults to FALSE. Note that this can substantially increase the number of models in the candidate set. Not recommended when there are factors with many levels. Alternatively character vector specifying which factor predictors to include as interactions. These must be contained within pred.vars.fact.
#' If factor.factor.interactions is set to TRUE the function automatically generates hard coded interaction variables up to the maximum number of predictors (see max.predictors below) using combn. New factors are generated by pasting the resulting unique combinations together. This method of generating interaction terms is necessary because smooth-factor interactions are specified as by arguments in calls to gam(m4). Because the full subsets function automatically checks for collinearity, there is no issue with constructing model sets with multiple factor arguments that are higher order factors of each other, as these are invariably collinear and subsequently removed (see cov.cutoff below). A user defined cor.matrix (see cor.matrix) need not include these hard coded interactions: rows and columns for any it does not name are computed from use.dat.
#'
#' @param smooth.smooth.interactions A logical value indicating if the function should include te smooths of second order continuous predictor interactions. If set to TRUE, all continuous predictors will be combined as bivariate calls to te. Alternatively character vector specifying which continuous predictors to include. These must be contained within pred.vars.cont.
#'
#' @param factor.smooth.interactions Default is the character vector pred.vars.fact, meaning that all factor predictors will be included as by arguments with all the continuous predictors. If factor.factor.interactions is TRUE, factor interactions variables will also be included as by arguments, yielding higher order interactions up to the specified model max.predictors. If a character vector is supplied, this must specify which factor variables should be included as "by" argument interaction terms with the continuous smooth predictors. If a list is supplied, this must be a named list containing the elements fact.vars, linear.vars, cont.vars, each a character vector indicating what predictors should be used to construct the factor smooth interactions. Note that specified factors, linear predictors and continuous predictors must also be included in their respective character vectors (pred.vars.fact, linear.vars, pred.vars.cont). If specified as NA no factor-continuous predictor interactions will be included.
#'
#' @param  max.predictors An integer indicating the maximum number of predictors to include in any one model.
#'
#' @param  cov.cutoff A numeric value between 0 and 1 indicating the correlation cutoff value to use for excluding collinear models, based on the cor.matrix (see below). The default value is 0.28 (see Graham MH (2003). It is highly recommended to keep this value low, as correlation among predictors can yield spurious results. Note that predictors with a correlation greater than the specified value will still appear in the model set but will never appear in the same model. Including highly correlated predictors can make interpreting variable importance values difficult.
#'
#' @param cor.matrix  A user-supplied pairwise correlation matrix, or NA (the default) to compute one from use.dat. When supplied it governs every stage that screens on correlation: which factor-factor interaction columns are built, which te smooth-smooth interaction terms are built, and which assembled candidate models are excluded. It must therefore carry a row and a column for every predictor named in pred.vars.cont, pred.vars.fact and linear.vars; any that are missing are reported by name. The hard coded factor interaction columns that setting factor.factor.interactions causes to be created are the exception, because which of them exist depends on the supplied matrix itself and so cannot be known in advance. Rows and columns for any of those the matrix does not carry are computed from use.dat and appended, leaving every supplied value as supplied. Each dimension is treated separately, so a name supplied as a column and not as a row keeps the column given for it and has only its row computed; because collinearity is screened in both directions, a value supplied in one dimension alone can tighten a screen but never loosen it. Computing them reads the data of every predictor, so this is the one case in which a predictor of a class check_correlations cannot classify has to be named in the supplied matrix along with the interaction columns. When supplied it replaces the automatic estimate rather than overriding it: except in the interaction case above, check_correlations is not called at all, and a predictor of a class it does not accept can be used. By default predictor correlations are evaluated via a call to check_correlations, a function taking a data.frame (containing all predictors) as argument and generating a correlation matrix comprised of: 1) correlation coefficients between all continuous predictors via a call to cor; 2) approximate correlation values between continuous predictors and factors, as the square root of the R2 value obtained via a call to lm, where the continuous predictor is modelled as a response and the factor variable as a single fixed factor; and 3) approximate correlations values between factor predictors, as the square root of the R2 value obtained via a call multinom (from package nnet, Venables & Ripley 2002). Note that any user constructed pairwise matrix can be passed to the function and used for pairwise exclusion of variables from individual models, subject to two rules. It must be two-dimensional: a matrix, a data.frame, or any other object with two dimensions, so the value Matrix::Matrix returns is accepted while a length-one value of any other class is not, and NA is reserved for the default. And it must not contain NA between two terms that are actually screened against cov.cutoff, which is reported by naming the pairs; an NA on a pair no screen compares is accepted, so which cells matter depends on max.predictors and on the interaction arguments. An NA between a variable named in null.terms and a predictor is accepted, that screen being null.cov.cutoff's rather than cov.cutoff's: where the reverse direction gives a value that value is used, and where neither direction does the pair is computed from use.dat.
#'
#' @param non.linear.correlations Set this argument to TRUE if you would like to exclude continuous predictor combinations that are potentially "correlated" through non-linear relationships. See ?check_non_linear_correlations for more details.
#'
#' @param k An integer indicating the dimension of the basis used to represent the smooth term (see ?s). The default value is 5. Higher values are not recommended unless a complex trend between the response variable and the continuous predictor variables is expected, and the data are sufficient to support this. k can be reduced to as low as 3 where there is trouble obtaining convergence, or sample size is low. Note that this must be set to override the default value, regardless of what k is used in the test.fit
#'
#' @param bs.arg Specification of the smoother to use, see ?s for more information on smoother provided in gam (mgcv). Note that all continuous predictors specified in pred.vars.cont will be fitted using the same smooth, unless they are also specified as linear.terms or cyclic.vars. Note that any specification of bs in test.fit is discarded.
#'
#' @param cyclic.vars NA if there are no cyclic predictors, or if there are cyclic predictors, a character vector containing the names of any of the continuous predictors that should be modelled as cyclic variables. Note that these must also be contained in the pred.vars.cont character vector. Please also note there are issues with bs='cc' and model selection as this uses by default shrinkage. With shrinkage, variables are retained in models but with zero edf, which makes interpretation of AICc and BIC confusing. To account for this always select only the most parsimonious model (that with the fewest parameters), not just that with the lowest AICc. Reported estimated degrees of freedom (edf) in the model output table represent the sum of the edf of the smooth terms plus the number of parametric coefficients. When cyclic variables are included and shrinkage is used, any estimated edf of the smooth terms that are less than 1 are reset to 1 before summing to ensure the the total number of predictors in the model is captured properly.
#'
#' @param linear.vars NA if there are no continuous predictors to be treated as linear (not fitted as smooths). Only use this where variables are clearly continuous in nature, but you are confident a linear relationship is valid. It may also be useful for continuous predictors that are not well distributed along the x-axis (ie, sampling was conducted in clumped distances from a feature of interest). Where this is necessary, transformations should be considered where they can be used to theoretically linearize response relationships. Does not need to be contained in vector pred.vars.cont
#'
#' @param null.terms A character vector indicating the form of any re smooths to be included in gam
#' [e.g. s(site,bs=re)] or any other fixed terms or smooths that the user wants to include in
#' the null model. Use of bs=re is an alternative way of fitting simple random structures that
#' avoids use of PQL and allows a the greater range of families available in gam.mgcv to be used.
#' see ?s and links therein. Note: make sure you use gam instead of uGamm to make sure PQL is not used.
#' To fit a correlation structure, pass MuMIn::uGamm(..., correlation = ...) as the test.fit. A fit produced by mgcv::gamm() directly cannot be used: it records no call, so the candidate models cannot be refitted from it, and generate_model_set stops saying so.
#'
#' @param null.cov.cutoff The correlation above which a predictor is dropped for being correlated with a variable named in null.terms. Defaults to 0.8. Terms supplied through null.terms are forced into every candidate model and are outside the cov.cutoff screen, which covers pred.vars.cont, pred.vars.fact and linear.vars only, so without this a candidate could be arbitrarily strongly correlated with a forced term and still appear in every model in the set. That inflates the variance of the forced term's estimate, which is frequently the term the analysis exists to estimate, and nothing in the output would indicate it. A separate cutoff, with a much looser default than cov.cutoff, because the two screens answer different questions: cov.cutoff decides which predictors may appear together, and this decides which predictor is so nearly a restatement of a forced term that fitting both is not informative. Set it to 1 to admit every predictor whatever its correlation with a forced term. A variable inside a bs='re' smooth is exempt from this screen, however the argument is written -- quoted either way, or wrapped in c(). A bs given as a variable rather than a literal is exempt too, since it cannot be read here and screening a grouping factor in error drops a legitimate predictor, while not screening a fixed term in error leaves the behaviour of earlier versions. A random-effect grouping factor is correlated with the predictors measured within it by construction -- with null.terms = "s(Location,Site,bs='re')" and Status nested in Location their correlation is 1 -- and that is the design of the study rather than collinearity to screen out. The screen applies to fixed forced terms, which compete with a candidate for the same variation. Correlations among the null.terms variables themselves are neither computed nor screened: those terms are forced in by your decision, and dropping one is what must not happen. Where the correlation estimate is asymmetric, as check_non_linear_correlations returns it, both directions are read and the larger is used, which is what the cov.cutoff screen already does. The correlations this screens on are returned by generate_model_set as null.term.correlations, each cell being the value screened on rather than one direction of it, whether or not anything is dropped, so they can be inspected even where no warning is raised; full_subsets_gam does not return them, its output being that of fit_model_set. A supplied cor.matrix is used for any pair it gives a value for, in either dimension, and every other pair is computed from use.dat, which is the ordinary case since a supplied matrix is indexed by predictor and a forced term is not one. A pair the matrix gives no value for, NA in each direction it has, is one of those others, computed rather than read as a correlation of zero, so a cell left empty does not decide that a predictor may be fitted alongside a forced term; a forced term can therefore be part supplied and part computed. Where that computation fails, which is what a predictor of a class check_correlations cannot classify causes, the screen is skipped with a warning rather than the call stopping. A variable named in null.terms that is not a column of use.dat, such as a function or a term written over several columns, is skipped, a correlation not being defined for it.
#'
#' @details The function constructs a complete model set based on the supplied arguments.
#' for more information see Fisher R, Wilson SK, Sin TM, Lee AC, Langlois TJ (2018) A simple function for full-subsets multiple regression in ecology with R. Ecology and Evolution
#' https://onlinelibrary.wiley.com/doi/abs/10.1002/ece3.4134
#' @export
#' @return A list of the following output files:
#'
#' n.mods - The number of candidate models generated, equal to length(mod.formula).
#'
#' predictor.correlations - The matrix of estimated predictor correlations returned by the function check_correlations and used for model exclusion based on cov.cutoff
#'
#' null.term.correlations - A matrix of the correlations between each variable named in null.terms and each candidate predictor, used for model exclusion based on null.cov.cutoff. Rows are the null.terms variables and columns the predictors; a variable whose correlations could not be computed and which the supplied cor.matrix gave no value for has no row, the warning naming it instead. NULL where null.terms is empty, where it names only random-effect grouping factors or no column of use.dat, where every predictor is itself a null.terms variable, or where the computation failed and the supplied cor.matrix gave no value for any pair, so that there is nothing to report. The element is always present in the returned list; it is its value that is NULL. Correlations among the null.terms variables are not included, being neither computed nor screened.
#'
#' mod.formula - A named list containing the model formula that were generated (and will be fitted by fit_model_set). The names are the candidate model names used in the modname column of fit_model_set's output.
#'
#' used.data - A data.frame which is identical to the data.frame initially supplied by the user, but with any hard coded interaction terms appended via cbind.
#'
#' test.fit - The test.fit supplied by the user, passed through so that fit_model_set can update it.
#'
#' included.vars - A character vector of the predictors included in the model set, used to build the variable inclusion columns of fit_model_set's output.
#' @examples
#' library(mgcv)
#' data(case_study1)
#' use.dat <- case_study1
#' use.dat$site <- as.factor(use.dat$site)
#' test.fit <- gam(Herbivore.abundance ~ s(depth, k = 3, bs = "cr") + s(site, bs = "re"),
#'                  family = tw(), data = use.dat)
#' model.set <- generate_model_set(
#'   use.dat = use.dat,
#'   test.fit = test.fit,
#'   pred.vars.cont = c("complexity", "depth"),
#'   pred.vars.fact = "ZONE",
#'   null.terms = "s(site,bs='re')",
#'   max.predictors = 2,
#'   k = 3
#' )
generate_model_set=function(use.dat,
                          test.fit,
                          pred.vars.cont=NA,
                          pred.vars.fact=NA,
                          cyclic.vars=NA,
                          linear.vars=NA,
                          factor.smooth.interactions=pred.vars.fact,
                          factor.factor.interactions=FALSE,
                          smooth.smooth.interactions=FALSE,
                          cov.cutoff=0.28,
                          cor.matrix=NA,
                          non.linear.correlations=FALSE,
                          max.predictors=3,
                          k=5,
                          bs.arg="'cr'",
                          null.terms="",
                          null.cov.cutoff=0.8){

  validate_use_dat(use.dat)
  validate_null_terms(null.terms)
  # Unvalidated, an NA gave an internal "missing value where TRUE/FALSE needed",
  # and a character or length-2 value was accepted silently -- the latter
  # recycling into two concatenated messages.
  if(!is.numeric(null.cov.cutoff)||length(null.cov.cutoff)!=1||
     is.na(null.cov.cutoff)||null.cov.cutoff<0){
    stop("null.cov.cutoff must be a single non-negative number, or 1 to admit every predictor whatever its correlation with a forced term.")}
  # Recorded before build_predictor_correlation_matrix() reassigns cor.matrix to
  # the resolved matrix. After that point the variable no longer says whether
  # the caller supplied anything, and the null-term screen needs to know.
  cor.matrix.supplied=cor_matrix_supplied(cor.matrix)
  validate_predictor_names(pred.vars.cont=pred.vars.cont,
                          pred.vars.fact=pred.vars.fact,linear.vars=linear.vars)
  validate_interaction_predictors(factor.factor.interactions=factor.factor.interactions,
                          smooth.smooth.interactions=smooth.smooth.interactions,
                          factor.smooth.interactions=factor.smooth.interactions,
                          pred.vars.cont=pred.vars.cont,pred.vars.fact=pred.vars.fact,
                          linear.vars=linear.vars)
  validate_factor_levels(use.dat=use.dat,pred.vars.fact=pred.vars.fact)

  all.predictors=unique(stats::na.omit(c(pred.vars.cont,pred.vars.fact,linear.vars)))
  included.vars=all.predictors

  null.fit.l=build_null_model(test.fit=test.fit,use.dat=use.dat,null.terms=null.terms)
  null.formula=null.fit.l$null.formula

  check_predictor_missingness(use.dat=use.dat,all.predictors=all.predictors)

  factors.l=resolve_factor_interactions(use.dat=use.dat,
                          pred.vars.fact=pred.vars.fact,
                          factor.factor.interactions=factor.factor.interactions,
                          factor.smooth.interactions=factor.smooth.interactions,
                          pred.vars.cont=pred.vars.cont,
                          linear.vars=linear.vars,
                          all.predictors=all.predictors,
                          max.predictors=max.predictors,
                          cov.cutoff=cov.cutoff,
                          cor.matrix=cor.matrix)
  use.dat=factors.l$use.dat
  pred.vars.fact=factors.l$pred.vars.fact
  interaction.terms=factors.l$interaction.terms
  linear.interaction.terms=factors.l$linear.interaction.terms

  # The correlation matrix is resolved before the te() terms are chosen, not
  # after, so that one matrix governs every stage that screens on correlation
  # (FSSgam_package#13). resolve_smooth_smooth_interactions() used to compute
  # its own from use.dat and ignore a supplied cor.matrix entirely, so a user
  # who supplied a matrix saying two predictors were uncorrelated still found
  # their te() term absent.
  #
  # The reorder is safe because this needs all.predictors including the
  # factor-interaction columns, which resolve_factor_interactions() has already
  # created, and does not need the te() term names: those are split into their
  # components before the matrix is indexed.
  all.predictors=stats::na.omit(unique(c(all.predictors,pred.vars.fact)))
  cor.matrix=build_predictor_correlation_matrix(use.dat=use.dat,
                          all.predictors=all.predictors,
                          non.linear.correlations=non.linear.correlations,
                          cor.matrix=cor.matrix,
                          derived.predictors=factors.l$factor.interaction.terms)

  smooth.smooth.interaction.terms=resolve_smooth_smooth_interactions(
                          pred.vars.cont=pred.vars.cont,
                          smooth.smooth.interactions=smooth.smooth.interactions,
                          cov.cutoff=cov.cutoff,
                          max.predictors=max.predictors,
                          cor.matrix=cor.matrix)

  # Screened against the terms null.terms forces into every candidate. Those
  # terms are outside cov.cutoff's matrix, which covers pred.vars.cont,
  # pred.vars.fact and linear.vars only, so a candidate could be arbitrarily
  # strongly correlated with a forced term and still be admitted to every model
  # in the set. The consequence is silent: it inflates the variance of the
  # forced term's estimate, which is frequently the term the analysis exists to
  # estimate (FSSgam_package#23).
  #
  # A separate cutoff, and a much looser default, because the two screens answer
  # different questions. cov.cutoff decides which predictors may appear
  # together; this decides which predictor is so nearly a restatement of a
  # forced term that fitting both is not informative.
  #
  # Correlations among the null.terms variables themselves are neither computed
  # nor screened. Those terms are forced in by the user's decision, and dropping
  # one is exactly what must not happen.
  null.vars=null_term_variables(null.terms=null.terms,use.dat=use.dat)
  null.term.correlations=build_null_term_correlations(use.dat=use.dat,
                          null.vars=null.vars,all.predictors=all.predictors,
                          non.linear.correlations=non.linear.correlations,
                          cor.matrix=cor.matrix,
                          cor.matrix.supplied=cor.matrix.supplied)
  screen.l=screen_against_null_terms(pred.vars.cont=pred.vars.cont,
                          pred.vars.fact=pred.vars.fact,linear.vars=linear.vars,
                          interaction.terms=interaction.terms,
                          linear.interaction.terms=linear.interaction.terms,
                          smooth.smooth.interaction.terms=smooth.smooth.interaction.terms,
                          null.term.correlations=null.term.correlations,
                          null.cov.cutoff=null.cov.cutoff)
  pred.vars.cont=screen.l$pred.vars.cont
  pred.vars.fact=screen.l$pred.vars.fact
  linear.vars=screen.l$linear.vars
  interaction.terms=screen.l$interaction.terms
  linear.interaction.terms=screen.l$linear.interaction.terms
  smooth.smooth.interaction.terms=screen.l$smooth.smooth.interaction.terms
  included.vars=setdiff(included.vars,screen.l$dropped)

  # Dropping predictors can leave fewer than max.predictors, and
  # enumerate_candidate_models() then stops with a message naming
  # max.predictors, which a user has no reason to connect to the drop they were
  # just warned about.
  if(length(screen.l$dropped)>0){
    remaining=length(stats::na.omit(unique(c(pred.vars.cont,pred.vars.fact,linear.vars))))
    if(remaining<max.predictors){
      stop(paste0("After dropping ",paste(screen.l$dropped,collapse=", "),
           " for correlation with a null.terms variable, ",remaining,
           " predictor(s) remain and max.predictors is ",max.predictors,
           ". Lower max.predictors, raise null.cov.cutoff, or remove the term ",
           "from null.terms."))}}

  use.mods=enumerate_candidate_models(pred.vars.cont=pred.vars.cont,
                          pred.vars.fact=pred.vars.fact,
                          linear.vars=linear.vars,
                          interaction.terms=interaction.terms,
                          linear.interaction.terms=linear.interaction.terms,
                          smooth.smooth.interaction.terms=smooth.smooth.interaction.terms,
                          max.predictors=max.predictors,
                          cor.matrix=cor.matrix,
                          cov.cutoff=cov.cutoff)

  mod.formula=build_model_formulas(use.mods=use.mods,
                          pred.vars.cont=pred.vars.cont,
                          pred.vars.fact=pred.vars.fact,
                          linear.vars=linear.vars,
                          linear.interaction.terms=linear.interaction.terms,
                          cyclic.vars=cyclic.vars,
                          k=k,
                          bs.arg=bs.arg,
                          null.terms=null.terms,
                          null.formula=null.formula,
                          test.fit=test.fit)

  # Is this too many models?
  n.mods=length(mod.formula)
  return(list(n.mods=n.mods,
              predictor.correlations=cor.matrix,
              null.term.correlations=null.term.correlations,
              mod.formula=mod.formula,
              used.data=use.dat,
              test.fit=test.fit,
              included.vars=included.vars))
} #------------------ end function --------------------------------------------#

# Internal helpers for generate_model_set(). Not exported.

# Confirms use.dat is a data.frame (not e.g. a tibble).
validate_use_dat=function(use.dat){
  # identical() rather than inherits(): this rejects a tibble or a data.table
  # deliberately, and inherits(x,"data.frame") accepts both.
  if(!identical(class(use.dat),"data.frame")){
    stop("use.dat must be a data.frame, perhaps you have a tibble? FSSgam does not currently support tibbles.")
  }
}

# Confirms null.terms is a single, non-missing character string (possibly "").
# Without this check, downstream nchar(null.terms) calls fail in confusing,
# type-dependent ways (e.g. NA errors "missing value where TRUE/FALSE needed",
# a length>1 vector errors "the condition has length > 1", and a bare numeric
# or logical value is silently accepted and spliced into a nonsense formula).
validate_null_terms=function(null.terms){
  if(!is.character(null.terms) || length(null.terms)!=1 || is.na(null.terms)){
    stop("null.terms must be a single character string (e.g. \"s(site,bs='re')\"), or \"\" if no null term is required.")
  }
}

# Rejects a predictor named twice in one argument, and a predictor named as both
# a factor and a continuous predictor.
#
# enumerate_candidate_models() deduplicates a candidate's terms before indexing
# the correlation matrix, so a candidate holding one term twice yields a 1x1
# sub-matrix whose triangles are both empty. max() of an empty vector warns and
# returns -Inf, which is below any cov.cutoff, so the candidate survived: the
# model set held "ZONE+ZONE" and the run emitted two "no non-missing arguments
# to max; returning -Inf" warnings naming nothing (FSSgam_package#28).
#
# pred.vars.cont and linear.vars are deliberately NOT checked against each
# other. Naming a predictor in both is the documented way to fit it linearly:
# setdiff(pred.vars.cont, linear.vars) decides which predictors get a smooth,
# so a name in both is one that does not. Checking across them broke that idiom,
# which the test suite caught.
#
# Reported here rather than downstream because only here is the repeated name
# known. It does not remove the empty-triangle case: the documented idiom of
# naming a predictor in both pred.vars.cont and linear.vars reaches it too, and
# is exempt from this check. exceeds_cutoff() is what stops the warning.
validate_predictor_names=function(pred.vars.cont,pred.vars.fact,linear.vars){
  named=list(pred.vars.cont=pred.vars.cont,pred.vars.fact=pred.vars.fact,
             linear.vars=linear.vars)
  named=lapply(named,function(x) as.character(stats::na.omit(x)))

  within=lapply(named,function(x) unique(x[duplicated(x)]))
  within=within[vapply(within,length,0L)>0]
  if(length(within)>0){
    stop(paste0("Each predictor may be named once within an argument. Named ",
         "twice: ",paste(vapply(names(within),function(a)
           paste0(paste(within[[a]],collapse=", ")," (",a,")"),""),
         collapse="; "),"."))}

  # The strings that separate the parts of a generated term name are reserved.
  # build_model_formulas() and build_factor_smooth_terms() find them with
  # grep(fixed=TRUE) over every term, not only over names this package
  # generated, so a predictor whose own name contains one is read as an
  # interaction: catch.by.effort, an ordinary variable name, produces
  # ~s(catch.by.effort) + s(catch, by = effort), which fails to fit and drops
  # out of the model set. It announced itself only through the "-Inf" warnings
  # that exceeds_cutoff() now suppresses (FSSgam_package#39).
  #
  # Rejected rather than escaped. Parsing a term name back into its parts is how
  # this package identifies interactions throughout, and making that parse
  # unambiguous is a larger change than this batch.
  # "+" joins the terms of a candidate name and "*" writes a linear
  # interaction, so a predictor containing either is parsed as more than one
  # term in the same way.
  reserved=c(".by.",".te.",".t.",".I.","+","*")
  offending=unique(unlist(lapply(named,function(x)
    x[vapply(x,function(v) any(vapply(reserved,function(r)
      grepl(r,v,fixed=TRUE),logical(1))),logical(1))])))
  if(length(offending)>0){
    stop(paste0("Predictor name(s) containing a reserved separator: ",
         paste(offending,collapse=", "),". The strings ",
         paste(reserved,collapse=", ")," separate the parts of a generated term ",
         "name, so a predictor whose name contains one is parsed as an ",
         "interaction. Rename the predictor."))}

  # "null" is the name given to the null model's own candidate, so a predictor
  # of that name produces two candidates called null. mod.formula[["null"]]
  # returns the first, build_inclusion_mat() matches the wrong row, and the
  # variable importance table zeroes (FSSgam_package#39).
  if("null" %in% unlist(named,use.names=FALSE)){
    stop(paste0("A predictor may not be named \"null\": that is the name of the ",
         "null model's candidate, so the model set would hold two candidates of ",
         "that name. Rename the predictor."))}

  # A name cannot be both a factor and a continuous predictor. Unlike the pair
  # above this is not an idiom: the two lists decide how the term is written
  # into the formula, and a name in both is written both ways.
  both=intersect(named$pred.vars.fact,c(named$pred.vars.cont,named$linear.vars))
  if(length(both)>0){
    stop(paste0("Predictor(s) named as both a factor and a continuous ",
         "predictor: ",paste(both,collapse=", "),
         ". Name each in pred.vars.fact or in pred.vars.cont/linear.vars, not both."))}
}


# Rejects a variable named in the character form of factor.factor.interactions
# or smooth.smooth.interactions that is not a predictor of this model set.
#
# Each argument had a check against the wrong set: factor.factor.interactions
# against colnames(use.dat), so any column was accepted, and
# smooth.smooth.interactions against rownames(cor.matrix), so the set depended
# on whether a cor.matrix was supplied and on what names it carried. A
# non-predictor named in either was screened against cov.cutoff and contributed
# interaction terms, while appearing in no other candidate, in included.vars, or
# in the variable-inclusion columns fit_model_set() returns
# (FSSgam_package#37).
#
# Checked here, against the predictor lists, so that neither depends on a
# supplied matrix and both are settled before either argument is consumed --
# factor.factor.interactions by resolve_factor_interactions(), which runs before
# the resolved correlation matrix exists, and smooth.smooth.interactions by
# resolve_smooth_smooth_interactions(), which runs after.
validate_interaction_predictors=function(factor.factor.interactions,
                          smooth.smooth.interactions,factor.smooth.interactions,
                          pred.vars.cont,pred.vars.fact,linear.vars){
  report=function(named,allowed,arg,requirement){
    if(!is.character(named)){return(invisible(NULL))}
    missing.vars=setdiff(as.character(stats::na.omit(named)),
                         as.character(stats::na.omit(allowed)))
    if(length(missing.vars)==0){return(invisible(NULL))}
    stop(paste0("Variable(s) ",paste(missing.vars,collapse=", ")," named in ",
         arg," are not predictors. Each must appear in ",requirement,"."))
  }
  report(factor.factor.interactions,pred.vars.fact,
         "factor.factor.interactions","pred.vars.fact")
  report(smooth.smooth.interactions,c(pred.vars.cont,linear.vars),
         "smooth.smooth.interactions","pred.vars.cont (or linear.vars)")

  # A name repeated within either argument is the third route to
  # FSSgam_package#28, and the one the other two checks miss.
  # factor.factor.interactions=c("fa","fa","fb") builds the interaction column
  # fa.I.fb twice, so use.dat gains two columns of that name -- the shape of
  # FSSgam_package#22 -- and the candidate set gains fa.I.fb+fa.I.fb. It used to
  # announce itself with the two "-Inf" warnings; exceeds_cutoff() removed those,
  # so without this check the route would be silent.
  repeated=function(named,arg){
    if(!is.character(named)){return(invisible(NULL))}
    x=as.character(stats::na.omit(named))
    dup=unique(x[duplicated(x)])
    if(length(dup)==0){return(invisible(NULL))}
    stop(paste0("Each variable may be named once in ",arg,". Named twice: ",
         paste(dup,collapse=", "),"."))
  }
  repeated(factor.factor.interactions,"factor.factor.interactions")
  repeated(smooth.smooth.interactions,"smooth.smooth.interactions")

  # The third interaction argument, in its character form. Its list form is
  # already validated where it is consumed; the character form was not, and
  # names factors exactly as factor.factor.interactions does.
  #
  # Skipped where it still holds its default, which is pred.vars.fact itself.
  # Otherwise a name repeated in pred.vars.fact is reported against an argument
  # the user never set, and validate_predictor_names() already reports it
  # against the one they did.
  if(is.character(factor.smooth.interactions)&&
     !identical(factor.smooth.interactions,pred.vars.fact)){
    report(factor.smooth.interactions,pred.vars.fact,
           "factor.smooth.interactions","pred.vars.fact")
    repeated(factor.smooth.interactions,"factor.smooth.interactions")}
}

# Rejects a factor predictor with fewer than two levels among the rows used.
#
# check_correlations() and check_non_linear_correlations() both fit lm() with
# such a factor as the predictor, which stops with "contrasts can be applied
# only to factors with 2 or more levels" -- an error naming neither the
# function, the argument, nor the predictor. That lm() is now wrapped in try()
# in both, so the cell is left NA rather than aborting the call, but a
# single-level factor is not a usable predictor in any case: it explains
# nothing, and an interaction column built from it is a copy of the other
# factor, so the model set holds the same model under two names
# (FSSgam_package#33).
#
# droplevels() first: a factor whose extra levels are declared but unobserved
# has one level in the data and is the same problem.
validate_factor_levels=function(use.dat,pred.vars.fact){
  named=as.character(stats::na.omit(pred.vars.fact))
  named=named[named %in% colnames(use.dat)]
  if(length(named)==0){return(invisible(NULL))}
  n.levels=vapply(named,function(v){
    x=use.dat[,v]
    if(!is.factor(x)){x=factor(x)}
    nlevels(droplevels(x))},integer(1))
  too.few=named[n.levels<2]
  if(length(too.few)==0){return(invisible(NULL))}
  stop(paste0("Factor predictor(s) with fewer than two observed levels: ",
       paste(paste0(too.few," (",n.levels[too.few],")"),collapse=", "),
       ". A factor taking one value explains nothing and cannot be screened ",
       "for collinearity; remove it from pred.vars.fact."))
}

# The variables named in null.terms that are columns of use.dat and are not
# random-effect grouping factors.
#
# null.terms is a formula fragment, not a variable list, so the variables are
# recovered by parsing it. A name that is not a column -- a function, or a term
# written over several columns -- is dropped rather than reported: a correlation
# is not defined for it, and null.terms accepts anything the formula accepts.
#
# A variable inside a bs='re' smooth is excluded, and this is the difference
# between screening something worth screening and breaking an ordinary
# specification. A random-effect grouping factor is correlated with the
# predictors measured within it by construction: in the companion repository's
# case study 2, null.terms is s(Location,Site,bs='re') and Status is nested in
# Location, so their correlation is 1. That is the design of the study, not
# collinearity to screen out, and dropping Status there would be wrong.
#
# The screen is for a forced term that competes with a candidate for the same
# variation -- a fixed effect the analysis must adjust for -- which is the case
# FSSgam_package#23 describes.
null_term_variables=function(null.terms,use.dat){
  if(!is.character(null.terms)||length(null.terms)!=1||nchar(null.terms)==0){
    return(character(0))}
  parsed=try(stats::as.formula(paste("~",null.terms)),silent=TRUE)
  if(inherits(parsed,"try-error")){return(character(0))}
  terms.chr=attr(stats::terms(parsed),"term.labels")
  # Whether a term sets bs to "re", read from the parsed call rather than by
  # matching the text. A regex over the text missed bs=c('re'), which mgcv
  # accepts and which fits the identical null model, so a nested factor was
  # dropped and the call stopped with a message naming max.predictors -- none of
  # them the cause.
  is.re=vapply(terms.chr,function(t){
    call.t=try(str2lang(t),silent=TRUE)
    if(inherits(call.t,"try-error")||!is.call(call.t)){return(FALSE)}
    bs=try(call.t[["bs"]],silent=TRUE)
    if(inherits(bs,"try-error")||is.null(bs)){return(FALSE)}
    val=try(eval(bs,envir=baseenv()),silent=TRUE)
    # A bs that cannot be evaluated here -- bs=mybs, a variable in the caller's
    # scope, which mgcv accepts -- is treated as a random effect rather than as
    # a fixed term. The two errors are not symmetric: screening a grouping
    # factor drops a legitimate predictor, and not screening a fixed term leaves
    # the previous behaviour. The safe direction is to exempt it.
    if(inherits(val,"try-error")){return(TRUE)}
    "re" %in% as.character(val)},logical(1))

  fixed.vars=unique(unlist(lapply(terms.chr[!is.re],function(t)
    all.vars(stats::as.formula(paste("~",t))))))
  # as.character() so the empty case returns character(0) rather than NULL:
  # unlist() of an empty list gives NULL, and every caller tests length() or
  # calls setdiff(), which cope either way, but a return type that varies is
  # worth not leaving.
  intersect(as.character(fixed.vars),colnames(use.dat))
}


# Correlations between each null.terms variable and each candidate predictor.
#
# A supplied cor.matrix is used for any pair it gives a value for, so a user who
# wants a particular value screened on can give one. Every other cell is
# computed from use.dat, which is the ordinary case: a supplied matrix is
# indexed by predictor and a forced term is not one, so requiring it to be named
# there would disable this screen for every caller who supplies a matrix --
# reinstating exactly the silence FSSgam_package#23 exists to end. A cell the
# matrix gives no value for, NA in each direction it has, is one of those other
# cells, not a supplied zero (FSSgam_package#41).
#
# Computing it does not undo FSSgam_package#13. That guarantee is that a
# supplied matrix replaces the automatic estimate for the predictors, so a
# predictor of a class check_correlations() cannot classify can be used. Only
# the null.vars block is computed here, and where that computation fails -- which
# is what such a predictor causes -- the screen is skipped with a warning rather
# than the call aborting. The FSSgam_package#13 caller still gets their model
# set, and is told their forced terms were not screened.
#
# Returns NULL where there is nothing to report, so the returned element is
# absent rather than an empty matrix, and calling code can test for it.
build_null_term_correlations=function(use.dat,null.vars,all.predictors,
                          non.linear.correlations,cor.matrix,cor.matrix.supplied){
  screened=setdiff(all.predictors,null.vars)
  if(length(null.vars)==0||length(screened)==0){return(NULL)}

  # Allocated over every forced term and every screened predictor, since neither
  # dimension of a supplied matrix is guaranteed to name every term. given
  # records which cells a supplied direction actually gave a value for; every
  # other cell is computed below.
  out=matrix(0,length(null.vars),length(screened),
             dimnames=list(null.vars,screened))
  given=matrix(FALSE,length(null.vars),length(screened),
               dimnames=list(null.vars,screened))

  if(isTRUE(cor.matrix.supplied)){
    supplied.m=as.matrix(cor.matrix)
    # A forced term named in EITHER dimension is used. Taking the rows from
    # rownames() alone discarded, in full, a matrix naming a forced term only as
    # a column, and substituted a computed estimate -- so a value the user
    # supplied to control the screen was ignored, and on the FSSgam_package#13
    # path the screen was skipped altogether. That is the third orientation of
    # the same asymmetry: the value read, the row shape, and now the column
    # shape.
    fill=function(acc,rows,cols.in,transpose){
      r=intersect(rows,rownames(supplied.m))
      c.=intersect(cols.in,colnames(supplied.m))
      if(length(r)==0||length(c.)==0){return(acc)}
      blk=abs(supplied.m[r,c.,drop=FALSE])
      if(transpose){blk=t(blk)}
      rn=rownames(blk)
      cn=colnames(blk)
      have=!is.na(blk)
      # Each direction is recorded before the two are combined, not after.
      # pmax() defaults to na.rm=FALSE, so combining first makes an NA in one
      # direction discard a real value in the other.
      blk[!have]=0
      acc$value[rn,cn]=pmax(acc$value[rn,cn,drop=FALSE],blk)
      acc$given[rn,cn]=acc$given[rn,cn,drop=FALSE]|have
      acc}

    acc=fill(list(value=out,given=given),null.vars,screened,transpose=FALSE)
    acc=fill(acc,screened,null.vars,transpose=TRUE)
    out=acc$value
    given=acc$given}

  # A pair the supplied matrix gives no value for in either direction is treated
  # as not supplied and computed from use.dat, the same as a forced term the
  # matrix does not name at all (FSSgam_package#41). Read as a correlation of
  # zero it admitted the predictor to every candidate alongside the forced term
  # -- the outcome FSSgam_package#23 exists to prevent -- decided by a cell the
  # user left empty rather than by a correlation, and where the same NA falls
  # between two predictors the cov.cutoff screen stops the call
  # (FSSgam_package#27). The distinction is made here rather than after the fill
  # inside fill(), since by then an unsupplied cell and a supplied zero are the
  # same number.
  to.compute=null.vars[apply(!given,1,any)]
  if(length(to.compute)==0){return(out)}
  # Not the complement of to.compute: a part-supplied row satisfies both. Used
  # only by the failure path below, which reports on to.compute and returns the
  # rows a supplied direction gave at least one value for.
  has.supplied=apply(given,1,any)

  full=try(if(non.linear.correlations==TRUE){
      check_non_linear_correlations(use.dat[,unique(c(to.compute,screened)),drop=FALSE])
    }else{
      check_correlations(use.dat[,unique(c(to.compute,screened)),drop=FALSE])},silent=TRUE)
  if(inherits(full,"try-error")){
    warning(paste0("Correlations between the null.terms variable(s) ",
            paste(to.compute,collapse=", ")," and the predictors could not be ",
            "computed, so ",
            if(any(has.supplied[to.compute])){
              "the pairs the supplied cor.matrix gave no value for were"
            }else{"those terms were"},
            " not screened against null.cov.cutoff: ",
            trimws(attr(full,"condition")$message)))
    # Only the rows a supplied direction gave at least one value for. A row
    # nothing was supplied for holds zeros that were never computed, so
    # returning it reports a correlation of zero for the pairs the warning has
    # just said were not screened -- the reading FSSgam_package#41 removes from
    # the supplied path, reintroduced on the failure path. NULL where no row
    # survives, which is what this function returns wherever there is nothing to
    # report.
    if(!any(has.supplied)){return(NULL)}
    return(out[has.supplied,,drop=FALSE])}
  full[is.na(full)]=0
  # Both directions, reduced to the larger. check_non_linear_correlations()
  # returns a deliberately asymmetric matrix -- row is the response, column the
  # predictor -- so [forced, predictor] and [predictor, forced] answer different
  # questions and only the second is large when a candidate is a deterministic
  # function of a forced term. Reading one direction admitted such a candidate
  # silently, which is the condition FSSgam_package#23 exists to end: measured
  # in the committed test, a squared forced term gives [forced, curve] 0.280,
  # below the default cutoff, and [curve, forced] 0.991.
  #
  # This is what the cov.cutoff screen already does: exceeds_cutoff() takes
  # max(abs()) over both triangles. On the symmetric default path the two
  # directions are equal and this changes nothing.
  # The computed matrix is square over these names and was zero-filled above,
  # so both directions exist and neither is NA; the supplied path above cannot
  # assume either.
  computed=pmax(abs(full[to.compute,screened,drop=FALSE]),
                abs(t(full[screened,to.compute,drop=FALSE])))
  # Only the cells no supplied direction gave a value for. A row can be part
  # supplied and part computed, so this is a cell-wise merge rather than a
  # choice between two blocks of rows.
  block=out[to.compute,screened,drop=FALSE]
  need=!given[to.compute,screened,drop=FALSE]
  block[need]=computed[need]
  out[to.compute,screened]=block
  out
}


# Drops any predictor whose correlation with a null.terms variable exceeds
# null.cov.cutoff, from every list a term can reach the candidate set through,
# and reports which and against what.
#
# A term that is not a bare predictor -- an interaction name -- is dropped when
# any of its parts is, since the term cannot be built without them.
screen_against_null_terms=function(pred.vars.cont,pred.vars.fact,linear.vars,
                          interaction.terms,linear.interaction.terms,
                          smooth.smooth.interaction.terms,null.term.correlations,
                          null.cov.cutoff){
  out=list(pred.vars.cont=pred.vars.cont,pred.vars.fact=pred.vars.fact,
           linear.vars=linear.vars,interaction.terms=interaction.terms,
           linear.interaction.terms=linear.interaction.terms,
           smooth.smooth.interaction.terms=smooth.smooth.interaction.terms,
           dropped=character(0))
  if(is.null(null.term.correlations)||nrow(null.term.correlations)==0){return(out)}

  over=abs(null.term.correlations)>null.cov.cutoff
  if(!any(over)){return(out)}
  dropped=colnames(null.term.correlations)[apply(over,2,any)]

  pairs=vapply(dropped,function(v){
    against=rownames(null.term.correlations)[over[,v]]
    worst=max(abs(null.term.correlations[against,v,drop=FALSE]))
    paste0(v," (",paste(against,collapse=", "),", max ",round(worst,3),")")},"")
  warning(paste0("Predictor(s) dropped, correlated with a null.terms variable ",
          "above null.cov.cutoff (",null.cov.cutoff,"): ",
          paste(pairs,collapse="; "),
          ". Raise null.cov.cutoff to keep them, or remove the term from ",
          "null.terms if it is not required in every model."))

  keep=function(x){
    if(length(stats::na.omit(x))==0){return(x)}
    kept=setdiff(stats::na.omit(x),dropped)
    if(length(kept)==0){NA}else{kept}}
  # An interaction name is split on every separator, so a term is dropped when
  # any part of it is.
  keep.terms=function(x){
    if(length(stats::na.omit(x))==0){return(x)}
    parts=strsplit(stats::na.omit(x),"\\.by\\.|\\.t\\.|\\.te\\.|\\.I\\.")
    kept=stats::na.omit(x)[!vapply(parts,function(p) any(p %in% dropped),logical(1))]
    if(length(kept)==0){NA}else{kept}}

  out$pred.vars.cont=keep(pred.vars.cont)
  out$pred.vars.fact=keep(pred.vars.fact)
  out$linear.vars=keep(linear.vars)
  out$interaction.terms=keep.terms(interaction.terms)
  out$linear.interaction.terms=keep.terms(linear.interaction.terms)
  out$smooth.smooth.interaction.terms=keep.terms(smooth.smooth.interaction.terms)
  out$dropped=dropped
  out
}

# Builds the null model formula and confirms test.fit can be updated to it.
# Returns list(null.formula=, null.fit=).
build_null_model=function(test.fit,use.dat,null.terms){
  # A bare mgcv::gamm() fit records no call, so stats::update() has nothing to
  # re-evaluate and every candidate refit fails. Reported here, before the
  # attempt, because the error update() gives -- "need an object with call
  # component" -- names neither the argument nor the remedy, and the message
  # below then advises the user to stop using uGamm, which is what they would
  # have had to use to succeed (FSSgam_package#34).
  #
  # gamm4 fits are a different class and are not affected; MuMIn::uGamm()
  # supplies the call that bare gamm() lacks, which is why it works.
  if(inherits(test.fit,"gamm")&&!inherits(test.fit,"gamm4")&&is.null(test.fit$call)){
    stop(paste0("A test.fit produced by mgcv::gamm() cannot be used: it records ",
         "no call, so the candidate models cannot be refitted from it. Fit the ",
         "same model through MuMIn::uGamm(), which supplies the call -- for a ",
         "correlation structure, uGamm(..., correlation = ...) -- or use gam() ",
         "with a bs='re' smooth if random effects are all that is required."))}

  if(nchar(null.terms)>0){
    null.formula=stats::as.formula(paste("~ ",null.terms,sep=""))}else{
    null.formula=stats::as.formula("~ 1")}

  if(length(grep("dsm",class(test.fit)))>0){
    null.fit=try(stats::update(test.fit,formula=null.formula),silent=TRUE)
  }else{
    # family= is intentionally omitted here, same reasoning as fit_mod_l()
    # in functions_supporting.R (see its comment) -- do not "fix" this by
    # adding family=stats::family(test.fit) back in.
    null.fit=try(stats::update(test.fit,formula=null.formula,data=use.dat),silent=TRUE)}

  if(inherits(null.fit,"try-error")){
        stop(paste("Null model not successfully fitted, please check your inputs.
                   If there are no random effects try using 'gam' instead of 'uGamm'
                   in your test.fit model call.",
                   " ",
                   "The following error message was provided:  ",
                   "  ",
                   null.fit, ""))}

  return(list(null.formula=null.formula,null.fit=null.fit))
}

# Stops if any predictor column contains missing values.
check_predictor_missingness=function(use.dat,all.predictors){
  if(anyNA(use.dat[,all.predictors])){
        stop("Predictor variables contain NA and AICc/BIC comparisons are invalid.
        Remove rows with NA from the input data or interpolate missing predictors.")}
}

# Builds hard-coded factor-factor interaction columns (if requested), coerces
# all factor predictors to class factor, and resolves the factor-smooth (.by.
# / .t.) interaction term names. Returns list(use.dat=, pred.vars.fact=,
# interaction.terms=, linear.interaction.terms=).
# The combination sizes to enumerate: every size from 2 up to max.size, capped
# at the number of variables available.
#
# The explicit empty case is the fix for a defect. This was written as
# `for(i in 2:n)`, and at n = 1 that sequence counts backwards to c(2, 1), so a
# size-1 "combination" was enumerated as well. Its pasted name is just the
# original variable name, so cbind() appended a duplicate column, and taking
# max() of the empty off-diagonal of a 1x1 sub-matrix warned "no non-missing
# arguments to max; returning -Inf" once per variable.
#
# n is min(max.size, length(vars)), so 2:n can never exceed the number of
# variables and needs no further filtering.
combination_sizes=function(vars,max.size){
  n=min(max.size,length(vars))
  if(n<2){return(integer(0))}
  2:n
}

# Every combination of `vars` at each size in `sizes`, dropping any whose
# sub-matrix of `cor.matrix` exceeds `cov.cutoff` off the diagonal. Returns a
# list of character vectors, possibly empty.
#
# Both triangles are screened, not just the upper one. The correlation
# matrices this is given are not necessarily symmetric: check_correlations()
# estimates a factor-factor value by fitting multinom() separately in each
# direction, and check_non_linear_correlations() is asymmetric by construction,
# its rows being responses and its columns predictors. Screening the upper
# triangle alone therefore accepted a pair whose correlation exceeded the
# cutoff in the other direction. Three of the four callers used to do exactly
# that.
#
# The `if (max(...) > cov.cutoff) out <- NA` shape is kept rather than reduced
# to a logical vector: max() of an all-NA sub-matrix returns NA, and `if (NA)`
# raises an error, which is the existing behaviour. A vapply() over a logical
# predicate would silently drop the combination instead.
combine_uncorrelated=function(vars,sizes,cor.matrix,cov.cutoff){
  combns=list()
  for(i in sizes){
    combns=c(combns,utils::combn(vars,i,simplify=FALSE))}
  combns=lapply(combns,FUN=function(x){
          # Defensive given the callers this function has: each pre-subsets
          # the matrix by name, so nothing reachable through the public API
          # distinguishes this from positional indexing, and no test pins it.
          # Reverting it fails nothing. Kept because a future caller passing an
          # unsubsetted matrix would need it.
          #
          # Indexed by name, both dimensions in the order of x, so that the
          # sub-matrix holds the pairs it is meant to. which(match(rownames, x))
          # returns positions in rowname order and which(match(colnames, x)) in
          # colname order, so where a matrix carries the same names in different
          # orders in its two dimensions the diagonal of the sub-matrix held
          # cross correlations and the triangles held the 1s of the original
          # diagonal, dropping the combination whatever its correlation.
          cor.mat.m=cor.matrix[x[x %in% rownames(cor.matrix)],
                               x[x %in% colnames(cor.matrix)],drop=FALSE]
          # Reported here, where the pair is known. An NA reaching the
          # comparison below stops the call with "missing value where
          # TRUE/FALSE needed", naming neither the matrix, the argument, nor
          # the pair (FSSgam_package#27).
          stop_on_na_correlations(cor.mat.m)
          out=x
          if(exceeds_cutoff(cor.mat.m,cov.cutoff)){out=NA}
          return(out)})
  combns[which(is.na(combns))]=NULL
  combns
}

# Pastes each surviving combination of factors into a new column named a.I.b
# and appends them to use.dat. Returns the extended data and the new names.
#
# Nothing is appended when there are no combinations. Reaching cbind() with a
# zero-column data.frame raises "arguments imply differing number of rows",
# which is what the character factor.factor.interactions branch used to do; the
# logical branch guarded against it. Warning about an empty result is left to
# the callers, which are the only place that can tell the two reasons for it
# apart.
build_factor_interaction_columns=function(use.dat,fact.combns){
  factor.interaction.terms=unlist(lapply(fact.combns,FUN=paste,collapse=".I."))

  # A generated name that is already a column of use.dat is declined rather
  # than appended. cbind() accepts the duplicate, and every later stage selects
  # predictors by name: use.dat[,"a.I.b"] returns the first of the two, which
  # is the user's own column, while the model formulas and the correlation
  # matrix were built for the generated one. They are different variables and
  # nothing reported the collision (FSSgam_package#22).
  #
  # Declining rather than overwriting, because overwriting silently changes a
  # predictor the user named. The combination is dropped from the returned term
  # names as well as from the columns, so no later stage refers to a term that
  # was not built.
  #
  # The shape arises without contrivance: running generate_model_set() twice and
  # passing the used.data of the first call as the use.dat of the second
  # presents every generated name as an existing column.
  # Two distinct combinations can paste to one name: (a, b.I.c) and (a.I.b, c)
  # both give a.I.b.I.c. The columns are different variables, so building both
  # gives use.dat two columns of that name -- the same defect as a collision
  # with a user's column, reached from inside rather than outside. It arises the
  # same way, by feeding used.data back in as use.dat, and announced itself only
  # through the "-Inf" warnings that exceeds_cutoff() now suppresses
  # (FSSgam_package#22, FSSgam_package#28).
  #
  # Screened before the collision check below, so a name colliding with both an
  # existing column and another generated name is reported once.
  #
  # Unreachable through the public API as it stands: producing two combinations
  # that paste to one name requires a predictor literally named a.I.b, and
  # validate_predictor_names() rejects a name containing a separator
  # (FSSgam_package#39). Kept as a guard, and pinned by no test -- do not read
  # its presence as coverage.
  self.colliding=duplicated(factor.interaction.terms)
  if(any(self.colliding)){
    warning(paste0("Factor interaction column(s) not created, because two ",
            "combinations of the named factors generate the same column name: ",
            paste(unique(factor.interaction.terms[self.colliding]),collapse=", "),
            ". Rename a factor if both interactions are wanted."))
    fact.combns=fact.combns[!self.colliding]
    factor.interaction.terms=factor.interaction.terms[!self.colliding]}

  colliding=factor.interaction.terms %in% colnames(use.dat)
  if(any(colliding)){
    warning(paste0("Factor interaction column(s) not created, because use.dat ",
            "already has a column of the same name: ",
            paste(factor.interaction.terms[colliding],collapse=", "),
            ". Rename the existing column(s) if the interaction is wanted."))
    fact.combns=fact.combns[!colliding]
    factor.interaction.terms=factor.interaction.terms[!colliding]}

  if(length(fact.combns)>0){
    tt=data.frame(lapply(fact.combns,FUN=function(x){
               do.call("paste",as.list(use.dat[,x]))}))
    colnames(tt)=factor.interaction.terms
    use.dat=cbind(use.dat,tt)}

  list(use.dat=use.dat,factor.interaction.terms=factor.interaction.terms)
}

# The warning for a collinearity screen that left nothing. Shared so the two
# factor.factor.interactions branches cannot drift apart again: the character
# branch used to be silent here.
warn_no_factor_interactions=function(cov.cutoff){
  warning(paste0("No factor-factor interaction terms were generated: every
                combination of the specified factors exceeded cov.cutoff (",
                cov.cutoff,")."))
}

# Normalises factor.smooth.interactions to one triple of variable sets.
#
# The character form names only the factors, and the continuous and linear
# predictors are taken from pred.vars.cont and linear.vars. The list form names
# all three itself, and is validated against all.predictors first -- a check
# the character form does not make, because pred.vars.fact has already been
# validated by the time it is reached.
normalise_factor_smooth_interactions=function(factor.smooth.interactions,
                          pred.vars.cont,linear.vars,all.predictors){
  if(inherits(factor.smooth.interactions,"list")){
    check.list=match(stats::na.omit(
    unlist(factor.smooth.interactions)),all.predictors)

    if(length(which(is.na(check.list)))>0){
            stop(paste("Variable(s)",
                       unlist(factor.smooth.interactions)[which(is.na(check.list))] ,
                       "included in the factor.smooth.interactions list do(es)
                       not appear in either pred.vars.fact, pred.vars.cont or linear.vars.
                       Please ensure all predictors are specified as one of these three types"))}

    return(list(fact.vars=factor.smooth.interactions$fact.vars,
                cont.vars=factor.smooth.interactions$cont.vars,
                linear.vars=factor.smooth.interactions$linear.vars))
  }
  list(fact.vars=factor.smooth.interactions,
       cont.vars=pred.vars.cont,
       linear.vars=linear.vars)
}

# Builds the ".by." and ".t." interaction term names from that triple.
#
# The requested factors are first expanded to include any hard-coded ".I."
# interaction column built from them, so naming a factor also brings in the
# interactions it participates in.
build_factor_smooth_terms=function(spec,pred.vars.fact){
  interaction.terms=NA
  linear.interaction.terms=NA

  # a hard coded ".I." interaction is included when every factor it was built
  # from was named
  fact.vars=pred.vars.fact[!vapply(strsplit(pred.vars.fact,split=".I.",fixed=TRUE),
     function(x){anyNA(match(x,spec$fact.vars))},logical(1))]

  if(length(stats::na.omit(fact.vars))>0){
   # pred.vars.cont=NA is a documented way to run without smooth predictors.
   # Without this guard expand.grid() pairs the NA itself with each factor,
   # producing a phantom "NA.by.<factor>" term. At max.predictors=1 that term
   # is discarded again before the model set is returned, and the only symptom
   # is enumerate_candidate_models() taking max() of an empty correlation
   # sub-matrix and warning; from max.predictors=2 it survives into the
   # candidate set as a model whose formula smooths the literal NA.
   if(length(stats::na.omit(spec$cont.vars))>0){
    all.interactions=expand.grid(spec$cont.vars,fact.vars)
    interaction.terms=paste(all.interactions$Var1,all.interactions$Var2,sep=".by.")}

   # now interactions between linear continous predictors and factors
   if(length(stats::na.omit(spec$linear.vars))>0){
    linear.interactions=expand.grid(spec$linear.vars,fact.vars)
    linear.interaction.terms=paste(linear.interactions$Var1,linear.interactions$Var2,
                               sep=".t.")}
   }

  list(interaction.terms=interaction.terms,
       linear.interaction.terms=linear.interaction.terms)
}

# cor.matrix here is the raw user-supplied matrix, or NA, not the resolved one.
# The resolved matrix is built over all.predictors, which includes the
# interaction columns this function creates, so it cannot exist yet
# (FSSgam_package#13).
resolve_factor_interactions=function(use.dat,pred.vars.fact,factor.factor.interactions,
                          factor.smooth.interactions,pred.vars.cont,linear.vars,
                          all.predictors,max.predictors,cov.cutoff,cor.matrix){
  factor_correlations=function(vars){
    # The same default test as build_predictor_correlation_matrix(). This was a
    # second copy of the length(cor.matrix)==1 sentinel, so a 1x1 supplied
    # matrix was discarded here as well (FSSgam_package#26).
    if(!cor_matrix_supplied(cor.matrix)){
      # Zero-filled, as build_predictor_correlation_matrix() does for the
      # matrix it computes. Without it a computed matrix reaches the screen
      # with NA in it -- check_correlations() returns NA for a pair involving
      # a single-level factor (FSSgam_package#33) -- and the report then named
      # a supplied cor.matrix when none had been supplied. The issue asserts
      # the computed branch can never reach that point; it can, by this route
      # (FSSgam_package#27).
      computed=check_correlations(use.dat[,vars])
      computed[is.na(computed)]=0
      computed
    }else{
      missing.vars=vars[which(is.na(match(vars,rownames(cor.matrix))))]
      if(length(missing.vars)>0){
        stop(paste("Supplied cor.matrix is missing required predictors: ",
             paste(missing.vars,collapse=", "),".",sep=""))}
      cor.matrix[vars,vars,drop=FALSE]}
  }
  interaction.terms=NA
  linear.interaction.terms=NA
  # The names of the hard coded interaction columns this function appends to
  # use.dat. Returned so that build_predictor_correlation_matrix() can tell a
  # predictor the user could have named from one this function invented
  # (FSSgam_package#15).
  factor.interaction.terms=character(0)

  # if there are factors
  if(length(stats::na.omit(pred.vars.fact))>0){
  # if there are two or more factors
  if(length(stats::na.omit(pred.vars.fact))>1){
    # make all the interactions between factors
    if(inherits(factor.factor.interactions,"logical")){
     if(factor.factor.interactions==TRUE){
        if(length(pred.vars.fact)<2){
            stop("You have less than 2 factors. Please reset 'factor.factor.interactions' to 'False'")}
      factor.correlations=factor_correlations(pred.vars.fact)
      # Two different reasons for building nothing, which need different
      # messages: max.predictors leaves no room for an interaction of two or
      # more factors, or combinations were enumerated and every one exceeded
      # cov.cutoff. warn.when.empty covers the second; the first is reported
      # here, because only this point knows max.predictors.
      fact.sizes=combination_sizes(pred.vars.fact,max.predictors)
      if(length(fact.sizes)==0){
        warning(paste0("factor.factor.interactions is TRUE but max.predictors is ",
                max.predictors,", so no interaction of two or more factors can be
                included. No factor-factor interaction terms were generated."))}
      fact.combns=combine_uncorrelated(vars=pred.vars.fact,
                          sizes=fact.sizes,
                          cor.matrix=factor.correlations,cov.cutoff=cov.cutoff)
      if(length(fact.sizes)>0 & length(fact.combns)==0){
        warn_no_factor_interactions(cov.cutoff)}
      cols.l=build_factor_interaction_columns(use.dat=use.dat,fact.combns=fact.combns)
      use.dat=cols.l$use.dat
      factor.interaction.terms=c(factor.interaction.terms,cols.l$factor.interaction.terms)
      pred.vars.fact=c(pred.vars.fact,cols.l$factor.interaction.terms)
      }
    }
    # make only specified interactions between factors
    if(inherits(factor.factor.interactions,"character")){
        if(length(factor.factor.interactions)<2){
            stop("You specified less than 2 factors as factor.factor.interactions.")}
        if(anyNA(match(factor.factor.interactions,colnames(use.dat)))){
            stop("Not all specified factor.factor.interactions are supplied in use.dat")}
      factor.correlations=factor_correlations(factor.factor.interactions)
      # An outer guard here, if(length(which(factor.correlations<cov.cutoff))>1),
      # used to skip this whole block in silence. It counted cells of the
      # correlation matrix below the cutoff rather than pairs, so two factors
      # whose two off-diagonal estimates straddle cov.cutoff gave a count of 1
      # and no interaction was built and nothing was reported. The logical
      # branch had no such guard. Removed: combine_uncorrelated() already
      # rejects a combination that exceeds the cutoff, and an empty result is
      # now warned about below.
      fact.sizes=combination_sizes(factor.factor.interactions,max.predictors)
      if(length(fact.sizes)==0){
        warning(paste0("max.predictors is ",max.predictors,", so no interaction of
                two or more of the specified factors can be included. No
                factor-factor interaction terms were generated."))}
      fact.combns=combine_uncorrelated(vars=factor.factor.interactions,
                          sizes=fact.sizes,
                          cor.matrix=factor.correlations,cov.cutoff=cov.cutoff)
      if(length(fact.sizes)>0 & length(fact.combns)==0){
        warn_no_factor_interactions(cov.cutoff)}
      cols.l=build_factor_interaction_columns(use.dat=use.dat,fact.combns=fact.combns)
      use.dat=cols.l$use.dat
      factor.interaction.terms=c(factor.interaction.terms,cols.l$factor.interaction.terms)
      pred.vars.fact=c(pred.vars.fact,cols.l$factor.interaction.terms)
    }
   }
   # make sure the factors are factors
   for(f in seq_along(pred.vars.fact)){
       use.dat[,pred.vars.fact[f]]=factor(use.dat[,pred.vars.fact[f]])}


   # check which factors should be included as interactions with the smoothers
   #
   # The character and list forms differ only in where the three variable sets
   # come from, so they are normalised to one triple and then handled once.
   # factor.smooth.interactions=NA is neither, and correctly falls through with
   # interaction.terms left at NA.
   if(inherits(factor.smooth.interactions,"character")|
      inherits(factor.smooth.interactions,"list")){
     spec=normalise_factor_smooth_interactions(
                          factor.smooth.interactions=factor.smooth.interactions,
                          pred.vars.cont=pred.vars.cont,linear.vars=linear.vars,
                          all.predictors=all.predictors)
     smooth.terms.l=build_factor_smooth_terms(spec=spec,pred.vars.fact=pred.vars.fact)
     interaction.terms=smooth.terms.l$interaction.terms
     linear.interaction.terms=smooth.terms.l$linear.interaction.terms
   }

   }

  return(list(use.dat=use.dat,
              pred.vars.fact=pred.vars.fact,
              factor.interaction.terms=factor.interaction.terms,
              interaction.terms=interaction.terms,
              linear.interaction.terms=linear.interaction.terms))
}

# Builds the names of the te() smooth-smooth interaction terms to consider,
# excluding any continuous-predictor pairs that exceed cov.cutoff. Returns a
# character vector (or NA if smooth.smooth.interactions is not requested).
resolve_smooth_smooth_interactions=function(pred.vars.cont,smooth.smooth.interactions,
                          cov.cutoff,max.predictors,cor.matrix){
   smooth.smooth.interaction.terms=NA
    # for interactions amongst all continuous predictors
    if(inherits(smooth.smooth.interactions,"logical")){
      if(smooth.smooth.interactions==TRUE){
        if(length(pred.vars.cont)<2){
            stop("You have less than 2 continuous predictors you wish interactions for.
            Please reset 'smooth.smooth.interactions' to 'False'")}
       # Subset of the matrix the caller resolved, rather than a fresh one
       # computed from use.dat. When no cor.matrix was supplied the two agree:
       # the continuous-continuous block does not depend on which other
       # predictors are present, checked against both check_correlations() and
       # check_non_linear_correlations() with a maximum absolute difference of
       # 0. When one was supplied, it now governs here too
       # (FSSgam_package#13).
       continuous.correlations=cor.matrix[pred.vars.cont,pred.vars.cont,drop=FALSE]

      # The size is fixed at 2 here while the character branch below goes up to
      # max.predictors. That difference is intentional, not an unfinished edit:
      # smooth.smooth.interactions = TRUE builds bivariate te() terms, and a
      # character vector builds terms of every size from 2 to max.predictors,
      # so te(a, b, c) is reachable only through the character form. The
      # documentation states both forms separately.
      #
      # combination_sizes(pred.vars.cont, 2) is 2 exactly, because the guard
      # above has already rejected fewer than two continuous predictors.
      cont.combns=combine_uncorrelated(vars=pred.vars.cont,
                          sizes=combination_sizes(pred.vars.cont,2),
                          cor.matrix=continuous.correlations,cov.cutoff=cov.cutoff)
      smooth.smooth.interaction.terms=unlist(lapply(cont.combns,FUN=paste,collapse=".te."))
     }
    }
    # for only specific interactions amongst continuous predictors
    if(inherits(smooth.smooth.interactions,"character")){
        if(length(smooth.smooth.interactions)<2){
            stop("You specified less than 2 variables as smooth.smooth.interactions.")}
        # Checked against the resolved correlation matrix, which is built over
        # the predictors, not against colnames(use.dat) as it used to be. A
        # column of use.dat that is not a predictor has no row in the matrix,
        # so it cannot be screened; it previously reached combine_uncorrelated()
        # with an empty sub-matrix and was admitted on a max() of nothing. The
        # message names the real requirement rather than repeating the old one.
        missing.cont=smooth.smooth.interactions[
                          which(is.na(match(smooth.smooth.interactions,rownames(cor.matrix))))]
        if(length(missing.cont)>0){
            stop(paste("Variable(s) ",paste(missing.cont,collapse=", "),
                 " named in smooth.smooth.interactions are not predictors. Each must",
                 " appear in pred.vars.cont (or linear.vars).",sep=""))}
      # see the matching comment in the logical branch above
      continuous.correlations=cor.matrix[smooth.smooth.interactions,
                                         smooth.smooth.interactions,drop=FALSE]

      cont.combns=combine_uncorrelated(vars=smooth.smooth.interactions,
                          sizes=combination_sizes(smooth.smooth.interactions,max.predictors),
                          cor.matrix=continuous.correlations,cov.cutoff=cov.cutoff)
      smooth.smooth.interaction.terms=unlist(lapply(cont.combns,FUN=paste,collapse=".te."))
    }

  return(smooth.smooth.interaction.terms)
}

# Resolves the predictor correlation matrix used for collinearity-based
# model exclusion: either computed from use.dat, or validated if the caller
# supplied their own cor.matrix.
# TRUE where any off-diagonal cell of the sub-matrix exceeds cov.cutoff.
#
# max() of an empty vector warns "no non-missing arguments to max" and returns
# -Inf. A 1x1 sub-matrix has empty triangles, and one arises whenever a
# candidate's deduplicated terms number one: from a predictor named twice, which
# is now rejected, and also from the documented idiom of naming a predictor in
# both pred.vars.cont and linear.vars, which is not. That idiom put the name in
# the pool twice and emitted the two warnings at any max.predictors of 2 or
# more, naming nothing (FSSgam_package#28).
#
# Returning FALSE for an empty triangle keeps the previous behaviour -- -Inf is
# below any cutoff, so the combination survived -- without the warning.
exceeds_cutoff=function(cor.mat.m,cov.cutoff){
  vals=c(cor.mat.m[upper.tri(cor.mat.m)],cor.mat.m[lower.tri(cor.mat.m)])
  if(length(vals)==0){return(FALSE)}
  max(abs(vals))>cov.cutoff
}

# Stops where the sub-matrix about to be screened against cov.cutoff has NA
# between two of its terms, naming the pairs.
#
# Called from the screening sites themselves rather than from a single earlier
# point. Two earlier placements were tried and both were wrong, in opposite
# directions. Checking only in build_predictor_correlation_matrix() missed every
# pair screened before it, resolve_factor_interactions() running first. Checking
# a union of every name that might be screened then reported pairs that are not:
# a name given in the character form of factor.factor.interactions is screened
# against the others in that argument and never against pred.vars.cont, so a
# union treats the Cartesian product as screened and fails on a cell nothing
# reads.
#
# The sub-matrix here is the one the screen is about to take max(abs(.)) of, so
# the pairs are exactly those that matter, and no model of which names reach
# which screen has to be maintained alongside the code that does the screening
# (FSSgam_package#27).
#
# Off-diagonal only: upper.tri() and lower.tri() exclude the diagonal, so a
# diagonal NA is never read.
stop_on_na_correlations=function(cor.mat.m){
  if(is.null(dim(cor.mat.m))||nrow(cor.mat.m)<2){return(invisible(NULL))}
  m=as.matrix(cor.mat.m)
  na.cells=which(is.na(m)&!diag(TRUE,nrow(m)),arr.ind=TRUE)
  if(nrow(na.cells)==0){return(invisible(NULL))}
  pairs=paste0(rownames(m)[na.cells[,"row"]],"/",colnames(m)[na.cells[,"col"]])
  # Worded so that it is true whichever matrix this is. Both computed paths are
  # zero-filled, so in practice only a supplied matrix reaches here -- but the
  # message said "Supplied cor.matrix" before the zero-fill in
  # factor_correlations() was added, and told users who had supplied nothing to
  # supply a correlation. Stating which matrix it is requires nothing extra.
  stop(paste0("The correlation matrix has NA between terms screened against ",
       "cov.cutoff: ",paste(unique(pairs),collapse=", "),
       ". If you supplied cor.matrix, supply a correlation for each of these ",
       "pairs, or remove the predictor."))
}

# TRUE where the caller supplied a correlation matrix, FALSE where they left the
# NA default and it is to be computed from use.dat.
#
# Tested on the default value rather than on length. length(cor.matrix)==1 was
# the sentinel, and a 1x1 matrix has length 1, so a model set with exactly one
# predictor -- the only case in which a supplied matrix is 1x1 -- had its
# supplied matrix silently discarded and recomputed (FSSgam_package#26).
#
# Anything that is neither a matrix, a data.frame, nor the NA default is
# rejected here. Under the old sentinel what happened to such a value depended
# on its length, and neither outcome was right: a length-one value of any class
# -- a string, a list holding a matrix -- satisfied the sentinel and was
# silently treated as nothing supplied, so the matrix was computed from use.dat
# and the model set built as though the argument had not been given; a value of
# any other length fell through to the supplied branch and failed against the
# missing-predictor check, reporting predictors rather than the argument.
cor_matrix_supplied=function(cor.matrix){
  # Tested on dimensionality rather than on a list of accepted classes. A
  # whitelist of matrix and data.frame rejected anything else two-dimensional,
  # including the S4 matrix Matrix::Matrix() returns, which worked before this
  # argument was validated at all. Matrix::nearPD() is not such a case: it
  # returns a list, and only its mat component was ever accepted.
  if(length(dim(cor.matrix))==2){return(TRUE)}
  if(length(cor.matrix)==1&&is.na(cor.matrix)){return(FALSE)}
  stop(paste0("cor.matrix must be a two-dimensional matrix or data.frame of predictor ",
       "correlations, or NA to have them computed from use.dat. Supplied: ",
       paste(class(cor.matrix),collapse="/"),
       " of length ",length(cor.matrix),"."))
}

build_predictor_correlation_matrix=function(use.dat,all.predictors,non.linear.correlations,
                          cor.matrix,derived.predictors=character(0)){
  if(!cor_matrix_supplied(cor.matrix)){
   # Computed only when the caller supplied nothing. It used to be computed
   # either way and then discarded in the else branch below, which meant a
   # supplied cor.matrix did not actually replace the automatic estimate: the
   # multinom() and gam() fits still ran, and a predictor of a class
   # check_correlations() rejects (a Date, say) still aborted the call even
   # though its correlations had been supplied. Nothing else in the function
   # reads it (FSSgam_package#13).
   #
   # drop=FALSE matters: with a single predictor use.dat[,all.predictors] would
   # otherwise collapse to a bare vector, and both check_* functions require a
   # data.frame (they classify columns via sapply(dat,class) and compare against
   # ncol(dat)). Without it, any model set with exactly one predictor failed
   # with an unrelated "argument is of length zero" error.
   if(non.linear.correlations==TRUE){
    cor.matrix=check_non_linear_correlations(use.dat[,all.predictors,drop=FALSE])}else{
    cor.matrix=check_correlations(use.dat[,all.predictors,drop=FALSE])}
   # Replace NA and NaN with zero. is.na() is TRUE for NaN as well, so this is
   # one pass rather than two; the NaN pass was written as
   # which(cor.matrix == "NaN"), which coerces the matrix to character and
   # happens to work.
   cor.matrix[is.na(cor.matrix)]=0}else{
      # A duplicated name makes the matrix ambiguous: which of the two rows
      # governs a screen depends on how the sub-matrix is indexed, and the
      # augmentation below keeps only one of them. Reported rather than
      # resolved arbitrarily.
      # Only a duplicated name that is a predictor of this model set, since only
      # those are indexed. A matrix carrying a duplicated name nothing reads is
      # accepted, as it is without a supplied matrix at all.
      duplicated.names=intersect(unique(c(
                                rownames(cor.matrix)[duplicated(rownames(cor.matrix))],
                                colnames(cor.matrix)[duplicated(colnames(cor.matrix))])),
                                all.predictors)
      if(length(duplicated.names)>0){
            stop(paste("Supplied cor.matrix has duplicated names: ",
            paste(duplicated.names,collapse=", "),".",sep=""))}

      # Tracked per dimension rather than pooled. A derived column the user
      # supplied as a column and not as a row is missing from the rows only, and
      # splicing computed values over both dimensions would overwrite the column
      # they did supply.
      missing.cols=all.predictors[which(is.na(match(all.predictors,colnames(cor.matrix))))]
      missing.rows=all.predictors[which(is.na(match(all.predictors,rownames(cor.matrix))))]
      missing.predictors=unique(c(missing.rows,missing.cols))

      # A predictor the user named and did not supply is still an error, so a
      # misspelled name is reported rather than quietly computed. A hard coded
      # factor interaction column is not: its name is invented by
      # resolve_factor_interactions() from the combinations that survive the
      # screen, which itself depends on the supplied matrix, so a user cannot
      # know in advance which of them to supply (FSSgam_package#15). Those rows
      # and columns are computed from use.dat instead.
      derived.missing.rows=intersect(missing.rows,derived.predictors)
      derived.missing.cols=intersect(missing.cols,derived.predictors)
      named.missing=setdiff(missing.predictors,derived.predictors)
      if(length(named.missing)>0){
            stop(paste("Supplied cor.matrix is missing required predictors: ",
            paste(named.missing,collapse=", "),".",sep=""))}
      if(length(derived.missing.rows)>0|length(derived.missing.cols)>0){
        cor.matrix=augment_supplied_correlation_matrix(use.dat=use.dat,
                          cor.matrix=cor.matrix,
                          derived.missing.rows=derived.missing.rows,
                          derived.missing.cols=derived.missing.cols,
                          all.predictors=all.predictors,
                          non.linear.correlations=non.linear.correlations)}
  }
  return(cor.matrix)
}

# Extends a supplied cor.matrix with rows and columns for the hard coded factor
# interaction columns the user could not have named (FSSgam_package#15).
#
# Every cell the user supplied is kept as supplied; only cells involving a
# derived column are computed. The computation needs the other predictors' data,
# so a predictor of a class check_correlations() rejects can no longer be used
# together with factor.factor.interactions and a supplied matrix. That is
# reported as such rather than as the class error on its own, since the caller
# has already supplied correlations for it.
#
# The supplied names are kept in their own order and the derived ones appended,
# rows and columns separately, so a matrix whose two dimnames differ is not
# reshaped into a square one with an invented all-NA row.
#
# A name the supplied matrix carries that is not a predictor of this model set
# has no computed value against a derived column. Those cells are set to zero,
# not left NA, which is what the branch that computes the whole matrix already
# does with the NA values check_correlations() returns. Leaving them NA is not
# safe: the character form of smooth.smooth.interactions validates its argument
# against the rownames of the resolved matrix rather than against the
# predictors, so such a name can reach combine_uncorrelated(), where max() of an
# all-NA sub-matrix returns NA and `if (NA)` raises an error naming neither the
# matrix nor the argument.
augment_supplied_correlation_matrix=function(use.dat,cor.matrix,derived.missing.rows,
                          derived.missing.cols,all.predictors,non.linear.correlations){
  derived.missing=unique(c(derived.missing.rows,derived.missing.cols))
  computed=try(if(non.linear.correlations==TRUE){
      check_non_linear_correlations(use.dat[,all.predictors,drop=FALSE])
    }else{
      check_correlations(use.dat[,all.predictors,drop=FALSE])},silent=TRUE)
  if(inherits(computed,"try-error")){
    stop(paste0("Supplied cor.matrix does not cover the hard coded factor ",
         "interaction predictor(s) ",paste(derived.missing,collapse=", "),
         ", and correlations for them could not be computed from use.dat: ",
         attr(computed,"condition")$message,
         " Either add rows and columns for them to cor.matrix, or use ",
         "predictors check_correlations can classify."))}
  computed[is.na(computed)]=0

  # as.matrix() because assigning a data.frame into a matrix sub-block replaces
  # the matrix with a plain list, dropping dim and dimnames, and the next
  # assignment then fails on what is no longer a matrix. A data.frame cor.matrix
  # is accepted everywhere else.
  cor.matrix=as.matrix(cor.matrix)
  row.vars=unique(c(rownames(cor.matrix),derived.missing.rows))
  col.vars=unique(c(colnames(cor.matrix),derived.missing.cols))
  out=matrix(NA_real_,nrow=length(row.vars),ncol=length(col.vars),
             dimnames=list(row.vars,col.vars))
  out[rownames(cor.matrix),colnames(cor.matrix)]=cor.matrix
  known.cols=intersect(col.vars,colnames(computed))
  known.rows=intersect(row.vars,rownames(computed))

  # Each dimension is spliced with its own set, so a derived name the user
  # supplied in one dimension keeps the values they gave for it there.
  if(length(derived.missing.rows)>0){
    out[derived.missing.rows,known.cols]=
      computed[derived.missing.rows,known.cols,drop=FALSE]
    new.rows=out[derived.missing.rows,,drop=FALSE]
    new.rows[is.na(new.rows)]=0
    out[derived.missing.rows,]=new.rows}
  if(length(derived.missing.cols)>0){
    out[known.rows,derived.missing.cols]=
      computed[known.rows,derived.missing.cols,drop=FALSE]
    new.cols=out[,derived.missing.cols,drop=FALSE]
    new.cols[is.na(new.cols)]=0
    out[,derived.missing.cols]=new.cols}
  out
}

# Enumerates every combination of available terms up to max.predictors, then
# removes redundant/invalid combinations (collinear above cov.cutoff, "by"
# terms without their main effect, more terms than max.predictors allows, a
# continuous predictor appearing both alone and inside an interaction).
# Returns the deduplicated list of valid term-name vectors.
enumerate_candidate_models=function(pred.vars.cont,pred.vars.fact,linear.vars,
                          interaction.terms,linear.interaction.terms,
                          smooth.smooth.interaction.terms,max.predictors,
                          cor.matrix,cov.cutoff){
  # make all possible combinations
  if(length(stats::na.omit(c(pred.vars.cont,linear.vars,
                      pred.vars.fact)))<max.predictors){
        stop("Model max.predictors is greater than the number of predictors.")}
  all.mods=list()
  for(i in 1:max.predictors){
    all.mods=c(all.mods,
     utils::combn(stats::na.omit(c(pred.vars.cont,pred.vars.fact,
                     linear.vars,
                     interaction.terms,
                     linear.interaction.terms,
                     smooth.smooth.interaction.terms)),
                     i,simplify=FALSE))
  }

  # remove redundant models
  use.mods=all.mods
  for(m in seq_along(all.mods)){
    mod.m=all.mods[[m]]
    mod.terms=unlist(strsplit(unlist(strsplit(unlist(strsplit(mod.m,
                               split=".by.",fixed=TRUE)),
                               split=".t.",fixed=TRUE)),
                               split=".te.",fixed=TRUE))
    n.vars.m=unique(unlist(strsplit(unlist(strsplit(unlist(strsplit(unlist(strsplit(mod.m,
                                  split=".by.",fixed=TRUE)),
                                  split=".I.",fixed=TRUE)),
                                  split=".t.",fixed=TRUE)),
                                  split=".te.",fixed=TRUE)))
    cont.vars=stats::na.omit(stats::na.omit(c(pred.vars.cont,linear.vars))[match(mod.terms,
                                           stats::na.omit(c(pred.vars.cont,linear.vars)))])
    fact.vars=unique(stats::na.omit(pred.vars.fact[match(mod.terms,pred.vars.fact)]))

    # if there are factor vars
    if(length(fact.vars)>0){
      # check that any "by" factor vars are accompanied by a + term in its owns right
      if(anyNA(match(fact.vars,mod.m))){use.mods[[m]]=NA}}

    # remove the model if the predictors are correlated
    if(length(mod.terms)>1){
     # see the matching comment in combine_uncorrelated()
     terms.m=unique(mod.terms)
     cor.mat.m=cor.matrix[terms.m[terms.m %in% rownames(cor.matrix)],
                          terms.m[terms.m %in% colnames(cor.matrix)],drop=FALSE]
     # see the matching comment in combine_uncorrelated()
     stop_on_na_correlations(cor.mat.m)
     if(exceeds_cutoff(cor.mat.m,cov.cutoff)){use.mods[[m]]=NA}
    }

    # remove the model if there are more than the number of terms specified in "max.predictors"
    if(length(n.vars.m)>max.predictors){use.mods[[m]]=NA}

    # remove the models if a continuous predictor occurs as a by, or a te, and as a single term
    if(length(cont.vars)>length(unique(cont.vars))){use.mods[[m]]=NA}

  }

  use.mods[which(is.na(use.mods))]=NULL

  # method="radix" sorts in byte order regardless of the session's LC_COLLATE.
  # Candidate names are built by sorting term names, so without it the same
  # analysis produced "complexity+ZONE" in an en_US.UTF-8 session and
  # "ZONE+complexity" in a C-locale one, and mod.data.out came back in a
  # different row order (FSSgam_package#8).
  use.mods=unique(lapply(use.mods,FUN=sort,method="radix"))

  return(use.mods)
}

# Converts the deduplicated term-name combinations (use.mods) into actual gam
# formula objects, handling smooth/by/te/linear/factor terms, cyclic.vars,
# and the null model. Returns the named list of formulas (including "null").
build_model_formulas=function(use.mods,pred.vars.cont,pred.vars.fact,linear.vars,
                          linear.interaction.terms,cyclic.vars,k,bs.arg,null.terms,
                          null.formula,test.fit){
  # now make the models into gamm formula
  if(nchar(null.terms)==0){# if there is no bs='re' random effect random effect
                             # or other null term in the null model
    mod.formula=list(stats::as.formula("~ 1"))}
  if(nchar(null.terms)>0){# to add a bs='re' random effect
    mod.formula=list(null.formula)}

  # The smoothing basis for one variable. Applied as each term is built, from
  # the variable name itself.
  #
  # This used to be done afterwards, by rewriting the assembled term strings:
  # grep(cyclic.vars[r], term) matched the name anywhere in the string and
  # treated it as a regular expression, so declaring "depth" cyclic also made
  # "depthx" cyclic, and a name containing "." matched any character. A second
  # block then existed only to repair the te() terms the first had damaged.
  # Both are gone.
  bs_for=function(v){
    if(v %in% stats::na.omit(cyclic.vars)){"'cc'"}else{bs.arg}}

  for(m in seq_along(use.mods)){
     mod.m=use.mods[[m]]
     cont.smooths=mod.m[which(match(mod.m,setdiff(pred.vars.cont,linear.vars))>0)]
     by.smooths=mod.m[grep(".by.",mod.m,fixed=TRUE)]
     te.smooths=mod.m[grep(".te.",mod.m,fixed=TRUE)]
     factor.terms=mod.m[which(match(mod.m,pred.vars.fact)>0)]
     linear.terms=mod.m[which(match(mod.m,linear.vars)>0)]
     # Matched against the .t. term names resolve_factor_interactions() actually
     # generated, the same way factor.terms and linear.terms are matched against
     # their own vectors. Two earlier forms were wrong. Building a pattern as
     # paste(linear.vars,".t.") made it a vector whenever more than one
     # linear.vars was supplied, and grep() then silently used only its first
     # element, so every interaction term belonging to a second or later linear
     # predictor was dropped from the fitted formula while the candidate kept
     # its interaction name. Deriving the prefixes from linear.vars here instead
     # fixed that, but still disagreed with the generator whenever the terms came
     # from factor.smooth.interactions$linear.vars, which is validated against
     # all.predictors rather than against linear.vars -- so the same silent drop
     # reappeared for a list-form factor.smooth.interactions naming a linear
     # predictor absent from linear.vars.
     linear.interaction.terms.m=mod.m[which(match(mod.m,linear.interaction.terms)>0)]
     all.terms.vec=character()

     if(length(cont.smooths)>0){all.terms.vec=c(all.terms.vec,
                  paste("s(",cont.smooths,",k=",k,",bs=",
                        vapply(cont.smooths,bs_for,character(1)),")",sep=""))}
     if(length(by.smooths)>0){
       # the smooth variable is the part before ".by."; the factor after it
       # carries no basis of its own
       all.terms.vec=c(all.terms.vec,
         paste("s(",gsub(".by.",",by=",by.smooths,fixed=TRUE),",k=",k,",bs=",
               vapply(sub("\\.by\\..*$","",by.smooths),bs_for,character(1)),")",sep=""))}
     if(length(te.smooths)>0){
       # one basis per marginal variable, in the order they appear in the name
       bs.vec=vapply(strsplit(te.smooths,".te.",fixed=TRUE),
                     function(v){paste0("bs=c(",
                        paste(vapply(v,bs_for,character(1)),collapse=","),")")},
                     character(1))
       te.fun=if(inherits(test.fit,"gamm4")){"t2("}else{"te("}
       all.terms.vec=c(all.terms.vec,
         paste(te.fun,gsub(".te.",",",te.smooths,fixed=TRUE),",k=",k,",",bs.vec,")",sep=""))}
      if(length(linear.interaction.terms.m)>0){all.terms.vec=c(all.terms.vec,
               gsub(".t.","*",linear.interaction.terms.m,fixed=TRUE))}
     if(length(factor.terms)>0){all.terms.vec=c(all.terms.vec,factor.terms)}
     if(length(linear.terms)>0){all.terms.vec=c(all.terms.vec,linear.terms)}

     if(nchar(null.terms)==0){# if there is no bs='re' random effect
                                # or other null term in the null model
       formula.m=stats::as.formula(paste("~",
               paste(all.terms.vec,collapse="+")))}
     if(nchar(null.terms)>0){#
       formula.m=stats::as.formula(paste("~",
               paste(c(all.terms.vec,null.terms),collapse="+")))}
     mod.formula=c(mod.formula,list(formula.m))
  }

  names(mod.formula)=c("null",lapply(use.mods,FUN=paste,collapse="+"))

  return(mod.formula)
}
